import { describe, expect, it } from "vitest";
import { call, isValidBuiltInFunctionName, lit, select, toSql, unsafeSql } from "../../src/index.js";

function restore(sql: string, mysql = false): string { const start = sql.startsWith("N'") ? 2 : 1; const body = sql.slice(start, -1); let result = ""; for (let i = 0; i < body.length; i++) { const c = body[i]!; if ((c === "'" || (mysql && c === "\\")) && body[i + 1] === c) i++; result += c; } return result; }
function outside(sql: string, marker: string): boolean { let quoted = false; for (let i = 0; i <= sql.length - marker.length; i++) { if (sql[i] === "'") { if (quoted && sql[i + 1] === "'") { i++; continue; } quoted = !quoted; continue; } if (!quoted && sql.slice(i, i + marker.length).toLowerCase() === marker.toLowerCase()) return true; } return false; }
function rng(seed: number) { let state = seed >>> 0; return (max: number) => ((state = (Math.imul(state, 1664525) + 1013904223) >>> 0) % max); }

describe("SQL literal and name safety", () => {
  it("ports AppendStringEscape_Basic", () => { for (const value of ["", "'", "z'", "'z", "z'z", "''", "') or ('1'='1--", "'; EXEC xp_cmdshell('whoami');--", "abc]];DROP TABLE [T];--"]) expect(restore(toSql(lit(value), { dialect: "mysql" }), true)).toBe(value); });
  it("ports AppendStringEscapeMySql_Backslash", () => { for (const value of ["'\\'", "a\\b'c"]) expect(restore(toSql(lit(value), { dialect: "mysql" }), true)).toBe(value); });
  it("ports CheckTSqlBuildInFunctionName_Valid", () => { for (const name of ["GETDATE", "DATEADD", "Coalesce", "@localVar", "@@ROWCOUNT", "A", "@a", "@@a"]) { expect(isValidBuiltInFunctionName(name)).toBe(true); expect(() => call(name)).not.toThrow(); } });
  it("ports CheckTSqlBuildInFunctionName_RejectsInjectionVectors", () => { for (const name of ["", "GETDATE;DROP TABLE T", "GETDATE --comment", "GET DATE", "1GETDATE", "GETDATE()", "GETDATE,DATEADD", "GETDATE/*x*/", "@@ROWCOUNT;SELECT 1"]) { expect(isValidBuiltInFunctionName(name)).toBe(false); expect(() => call(name)).toThrow(); } });
  it("ports LiteralEscaping_FuzzRoundTrip_AllExporters", () => { const next = rng(123456); const alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789 '\"`\\;/*-_=+[](){}:,.$#@!?%\r\n\t\b"; for (let n = 0; n < 500; n++) { let value = ""; const length = next(40); for (let i = 0; i < length; i++) value += alphabet[next(alphabet.length)]; if (next(4) === 0) value += "©"; if (next(5) === 0) value += "€"; if (next(6) === 0) value += "中"; for (const dialect of ["tsql", "postgresql", "mysql"] as const) expect(restore(toSql(lit(value), { dialect }), dialect === "mysql")).toBe(value); } });
  it("ports DangerousMarkers_DoNotEscapeLiteralBoundary", () => { const payloads = ["'; EXEC xp_cmdshell('whoami');--", "/*comment*/' OR 'x'='x", "UNION SELECT username,password FROM members--", "abc]];DROP TABLE [T];--", "abc``;DROP TABLE `T`;--", "abc\"\";DROP TABLE \"T\";--", "1); WAITFOR DELAY '00:00:05'--"]; for (const dialect of ["tsql", "postgresql", "mysql"] as const) { const sql = toSql(select(Object.fromEntries(payloads.map((value, i) => [`v${i}`, value]))), { dialect }); for (const marker of ["xp_cmdshell", "union select", "drop table", "waitfor delay", "/*", "--"]) expect(outside(sql, marker)).toBe(false); } });
  it("ports CheckTSqlBuildInFunctionName_FuzzInvalid", () => { const next = rng(98765); const alphabet = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_@$-;/* ()\t\r\n,.`'\"[]{}:=+!\\"; let tested = 0; for (let n = 0; n < 3000; n++) { let value = ""; const length = next(25); for (let i = 0; i < length; i++) value += alphabet[next(alphabet.length)]; if (/^(?:@@?)?\p{L}[\p{L}\p{N}_]*$/u.test(value)) continue; tested++; expect(isValidBuiltInFunctionName(value)).toBe(false); expect(() => call(value)).toThrow(); } expect(tested).toBeGreaterThan(1000); });
  it("ports UnsafeValue_EmitsRawSql", () => { const payload = "1; DROP TABLE Users --"; const raw = toSql(select({ value: unsafeSql(payload) }), { dialect: "tsql" }); const safe = toSql(select({ value: payload }), { dialect: "tsql" }); expect(outside(raw, "drop table")).toBe(true); expect(outside(safe, "drop table")).toBe(false); });
});
