// <auto-generated/>
#nullable enable
using SqExpress.TableDeclarationAttributes;

namespace SqExpress.EfCodeGenIntTest.Tables
{
    [TableDescriptor("catalog", "Products")]
    [Int32Column("ProductId", Pk = true, Identity = true)]
    [Int32Column("CategoryId", FkTable = "Categories", FkColumn = "CategoryId")]
    [BooleanColumn("IsDiscontinued", DefaultValue = "$raw(0)")]
    [StringColumn("Name", Unicode = true, MaxLength = 200)]
    [DecimalColumn("Price", Precision = 19, Scale = 4)]
    [StringColumn("Sku", MaxLength = 32)]
    [Index("Sku", Unique = true)]
    [Index("CategoryId", "Price")]
    public partial class TableProducts
    {
    }
}