// <auto-generated/>
#nullable enable
using SqExpress.TableDeclarationAttributes;

namespace SqExpress.EfCodeGenIntTest.Tables
{
    [TableDescriptor("sales", "OrderLines")]
    [Int64Column("OrderId", Pk = true, FkTable = "Orders", FkColumn = "OrderId")]
    [Int16Column("LineNo", Pk = true)]
    [Int32Column("ProductId", FkSchema = "catalog", FkTable = "Products", FkColumn = "ProductId")]
    [Int32Column("Quantity", DefaultValue = "$raw(1)")]
    [DecimalColumn("UnitPrice", Precision = 19, Scale = 4)]
    [Index("ProductId", "Quantity")]
    public partial class TableOrderLines
    {
    }
}