// <auto-generated/>
#nullable enable
using SqExpress.TableDeclarationAttributes;

namespace SqExpress.EfCodeGenIntTest.Tables
{
    [TableDescriptor("audit", "AuditLogs")]
    [Int64Column("AuditLogId", Pk = true, Identity = true)]
    [DateTimeColumn("CreatedUtc", DefaultValue = "$utcNow")]
    [StringColumn("EntityName", MaxLength = 128)]
    [StringColumn("Message", Unicode = true)]
    [Index("EntityName", "CreatedUtc", DescendingColumns = new string[] { "CreatedUtc" })]
    public partial class TableAuditLogs
    {
    }
}