// <auto-generated/>
#nullable enable
using SqExpress.TableDeclarationAttributes;

namespace SqExpress.EfCodeGenIntTest.Tables
{
    [TableDescriptor("catalog", "Categories")]
    [Int32Column("CategoryId", Pk = true, Identity = true)]
    [StringColumn("Name", Unicode = true, MaxLength = 100)]
    [Index("Name", Unique = true)]
    public partial class TableCategories
    {
    }
}