<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <SqModelGenEnable>false</SqModelGenEnable>
    <SqModelGenInput>.</SqModelGenInput>
    <SqModelGenOutput>Models</SqModelGenOutput>
    <SqModelGenNamespace>$(MSBuildProjectName).Models</SqModelGenNamespace>
    <SqModelGenCleanOutput>True</SqModelGenCleanOutput>
    <SqModelGenType>Record</SqModelGenType>
    <SqTablseGenOutput>Tables</SqTablseGenOutput>
    <SqTablseGenNamespace>$(MSBuildProjectName).Tables</SqTablseGenNamespace>
    <SqTablseGenTableClassPrefix></SqTablseGenTableClassPrefix>
    <SqTablseGenUseTableDeclarationAttributes Condition="'$(SqTablseGenUseTableDeclarationAttributes)' == ''"></SqTablseGenUseTableDeclarationAttributes>
    <SqTablseGenSkipUnknownColumnTypes Condition="'$(SqTablseGenSkipUnknownColumnTypes)' == ''"></SqTablseGenSkipUnknownColumnTypes>
    <SqTablseGenSplitTablesBySchema Condition="'$(SqTablseGenSplitTablesBySchema)' == ''"></SqTablseGenSplitTablesBySchema>
    <SqTablseGenCleanOutput>false</SqTablseGenCleanOutput>
    <SqTablseGenInclude></SqTablseGenInclude>
    <SqTablseGenExclude></SqTablseGenExclude>
    <SqTablesGenOutput Condition="'$(SqTablesGenOutput)' == ''"></SqTablesGenOutput>
    <SqTablesGenNamespace Condition="'$(SqTablesGenNamespace)' == ''"></SqTablesGenNamespace>
    <SqTablesGenTableClassPrefix Condition="'$(SqTablesGenTableClassPrefix)' == ''"></SqTablesGenTableClassPrefix>
    <SqTablesGenUseTableDeclarationAttributes Condition="'$(SqTablesGenUseTableDeclarationAttributes)' == ''"></SqTablesGenUseTableDeclarationAttributes>
    <SqTablesGenSkipUnknownColumnTypes Condition="'$(SqTablesGenSkipUnknownColumnTypes)' == ''"></SqTablesGenSkipUnknownColumnTypes>
    <SqTablesGenSplitTablesBySchema Condition="'$(SqTablesGenSplitTablesBySchema)' == ''"></SqTablesGenSplitTablesBySchema>
    <SqTablesGenCleanOutput Condition="'$(SqTablesGenCleanOutput)' == ''"></SqTablesGenCleanOutput>
    <SqTablesGenInclude Condition="'$(SqTablesGenInclude)' == ''"></SqTablesGenInclude>
    <SqTablesGenExclude Condition="'$(SqTablesGenExclude)' == ''"></SqTablesGenExclude>
    <SqExpressCodeGenPath>$(MSBuildThisFileDirectory)../tools/codegen/SqExpress.CodeGenUtil.dll</SqExpressCodeGenPath>
    <SqEfTablesGenEnable>false</SqEfTablesGenEnable>
    <SqEfTablesGenProject></SqEfTablesGenProject>
    <SqEfTablesGenDbContext></SqEfTablesGenDbContext>
    <SqEfTablesGenFramework></SqEfTablesGenFramework>
  </PropertyGroup>
</Project>
