<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <SqModelGenEnable>false</SqModelGenEnable>
    <SqModelGenInput>.</SqModelGenInput>
    <SqModelGenOutput>Models</SqModelGenOutput>
    <SqModelGenNamespace>$(MSBuildProjectName).Models</SqModelGenNamespace>
    <SqModelGenCleanOutput>True</SqModelGenCleanOutput>
    <SqModelGenType>Record</SqModelGenType>
    <SqTablseGenOutput>Tables</SqTablseGenOutput>
    <SqTablseGenNamespace>$(MSBuildProjectName).Tables</SqTablseGenNamespace>
    <SqTablseGenTableClassPrefix></SqTablseGenTableClassPrefix>
    <SqExpressCodeGenPath>$(MSBuildThisFileDirectory)../tools/codegen/SqExpress.CodeGenUtil.dll</SqExpressCodeGenPath>
    <SqEfTablesGenEnable>false</SqEfTablesGenEnable>
    <SqEfTablesGenProject></SqEfTablesGenProject>
    <SqEfTablesGenOutput>Tables</SqEfTablesGenOutput>
    <SqEfTablesGenNamespace>$(MSBuildProjectName).Tables</SqEfTablesGenNamespace>
    <SqEfTablesGenTableClassPrefix></SqEfTablesGenTableClassPrefix>
    <SqEfTablesGenDbContext></SqEfTablesGenDbContext>
    <SqEfTablesGenFramework></SqEfTablesGenFramework>
    <SqEfTablesGenUseTableDeclarationAttributes>true</SqEfTablesGenUseTableDeclarationAttributes>
    <SqEfTablesGenSkipUnknownColumnTypes>true</SqEfTablesGenSkipUnknownColumnTypes>
  </PropertyGroup>
</Project>
