// <auto-generated/>
#nullable enable
using SqExpress.TableDeclarationAttributes;

namespace SqExpress.EfCodeGenIntTest.Tables.Sales
{
    [TableDescriptor("sales", "Customers")]
    [Int32Column("CustomerId", Pk = true, Identity = true)]
    [NullableByteArrayColumn("BinaryCode", MaxLength = 16)]
    [StringColumn("Code", MaxLength = 12, FixedLength = true)]
    [DateTimeColumn("CreatedUtc", DefaultValue = "$utcNow")]
    [NullableDecimalColumn("CreditLimit", Precision = 18, Scale = 2)]
    [Int64Column("ExternalNumber")]
    [ByteArrayColumn("FixedBinaryCode", MaxLength = 8, FixedLength = true)]
    [BooleanColumn("IsActive", DefaultValue = "$raw(1)")]
    [NullableDateTimeOffsetColumn("LastSeenAt")]
    [Int16Column("LegacyCode", DefaultValue = "$raw(7)")]
    [NullableXmlColumn("MetadataXml")]
    [StringColumn("Name", Unicode = true, MaxLength = 200)]
    [NullableInt32Column("ParentCustomerId")]
    [GuidColumn("PublicId", DefaultValue = "$raw((newid()))")]
    [ByteColumn("RiskLevel", DefaultValue = "$raw(1)")]
    [DoubleColumn("Score", DefaultValue = "$raw(0)")]
    [Index("Code", Unique = true)]
    [Index("Name", "CreatedUtc", DescendingColumns = new string[] { "CreatedUtc" })]
    public partial class TableCustomers
    {
    }
}