// <auto-generated/>
#nullable enable
using SqExpress.TableDeclarationAttributes;

namespace SqExpress.EfCodeGenIntTest.Tables.Sales
{
    [TableDescriptor("sales", "Orders")]
    [Int64Column("OrderId", Pk = true, Identity = true)]
    [DateTimeColumn("CreatedUtc", DefaultValue = "$utcNow")]
    [Int32Column("CustomerId", FkTable = "Customers", FkColumn = "CustomerId")]
    [StringColumn("OrderNumber", MaxLength = 32)]
    [DecimalColumn("Total", Precision = 19, Scale = 4)]
    [Index("OrderNumber", Unique = true)]
    [Index("CustomerId", "CreatedUtc", DescendingColumns = new string[] { "CreatedUtc" })]
    public partial class TableOrders
    {
    }
}