using System;
using SqExpress;
using SqExpress.QueryBuilders.RecordSetter;
using SqExpress.GetStarted;
using SqExpress.Syntax.Names;
using System.Collections.Generic;
using SqExpress.GetStarted.Models.Extra;
using SqExpress.Syntax.Select.SelectItems;

namespace SqExpress.GetStarted.Models
{
    public class CompanyName : IModel
    {
        //Auto-generated by SqExpress Code-gen util
        public CompanyName(int id, string name)
        {
            this.Id = id;
            this.Name = name;
        }

        //Auto-generated by SqExpress Code-gen util
        public static CompanyName Read(ISqDataRecordReader record, TableCompany table)
        {
            return new CompanyName(id: table.CompanyId.Read(record), name: table.CompanyName.Read(record));
        }

        //Auto-generated by SqExpress Code-gen util
        public static CompanyName ReadWithPrefix(ISqDataRecordReader record, TableCompany table, string prefix)
        {
            return new CompanyName(id: table.CompanyId.Read(record, prefix + table.CompanyId.ColumnName.Name), name: table.CompanyName.Read(record, prefix + table.CompanyName.ColumnName.Name));
        }

        //Auto-generated by SqExpress Code-gen util
        public static CompanyName ReadOrdinal(ISqDataRecordReader record, TableCompany table, int offset)
        {
            return new CompanyName(id: table.CompanyId.Read(record, offset), name: table.CompanyName.Read(record, offset + 1));
        }

        //Auto-generated by SqExpress Code-gen util
        public int Id { get; }

        //Auto-generated by SqExpress Code-gen util
        public string Name { get; }

        //Auto-generated by SqExpress Code-gen util
        public CompanyName WithId(int id)
        {
            return new CompanyName(id: id, name: this.Name);
        }

        //Auto-generated by SqExpress Code-gen util
        public CompanyName WithName(string name)
        {
            return new CompanyName(id: this.Id, name: name);
        }

        //Auto-generated by SqExpress Code-gen util
        public static TableColumn[] GetColumns(TableCompany table)
        {
            return new TableColumn[]{table.CompanyId, table.CompanyName};
        }

        //Auto-generated by SqExpress Code-gen util
        public static ExprAliasedColumn[] GetColumnsWithPrefix(TableCompany table, string prefix)
        {
            return new ExprAliasedColumn[]{table.CompanyId.As(prefix + table.CompanyId.ColumnName.Name), table.CompanyName.As(prefix + table.CompanyName.ColumnName.Name)};
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNull(ISqDataRecordReader record, TableCompany table)
        {
            foreach (var column in GetColumns(table))
            {
                if (!record.IsDBNull(column.ColumnName.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNullWithPrefix(ISqDataRecordReader record, TableCompany table, string prefix)
        {
            foreach (var column in GetColumnsWithPrefix(table, prefix))
            {
                if (!record.IsDBNull(column.Alias!.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetMapping(IDataMapSetter<TableCompany, CompanyName> s)
        {
            return s.Set(s.Target.CompanyName, s.Source.Name);
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetUpdateKeyMapping(IDataMapSetter<TableCompany, CompanyName> s)
        {
            return s.Set(s.Target.CompanyId, s.Source.Id);
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetUpdateMapping(IDataMapSetter<TableCompany, CompanyName> s)
        {
            return s.Set(s.Target.CompanyName, s.Source.Name);
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelReader<CompanyName, TableCompany> GetReader()
        {
            return CompanyNameReader.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class CompanyNameReader : ISqModelReader<CompanyName, TableCompany>
        {
            public static CompanyNameReader Instance { get; } = new CompanyNameReader();
            IReadOnlyList<ExprColumn> ISqModelReader<CompanyName, TableCompany>.GetColumns(TableCompany table)
            {
                return CompanyName.GetColumns(table);
            }

            CompanyName ISqModelReader<CompanyName, TableCompany>.Read(ISqDataRecordReader record, TableCompany table)
            {
                return CompanyName.Read(record, table);
            }

            CompanyName ISqModelReader<CompanyName, TableCompany>.ReadOrdinal(ISqDataRecordReader record, TableCompany table, int offset)
            {
                return CompanyName.ReadOrdinal(record, table, offset);
            }
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelUpdaterKey<CompanyName, TableCompany> GetUpdater()
        {
            return CompanyNameUpdater.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class CompanyNameUpdater : ISqModelUpdaterKey<CompanyName, TableCompany>
        {
            public static CompanyNameUpdater Instance { get; } = new CompanyNameUpdater();
            IRecordSetterNext ISqModelUpdater<CompanyName, TableCompany>.GetMapping(IDataMapSetter<TableCompany, CompanyName> dataMapSetter)
            {
                return CompanyName.GetMapping(dataMapSetter);
            }

            IRecordSetterNext ISqModelUpdaterKey<CompanyName, TableCompany>.GetUpdateKeyMapping(IDataMapSetter<TableCompany, CompanyName> dataMapSetter)
            {
                return CompanyName.GetUpdateKeyMapping(dataMapSetter);
            }

            IRecordSetterNext ISqModelUpdaterKey<CompanyName, TableCompany>.GetUpdateMapping(IDataMapSetter<TableCompany, CompanyName> dataMapSetter)
            {
                return CompanyName.GetUpdateMapping(dataMapSetter);
            }
        }
    }
}