using System;
using SqExpress;
using SqExpress.QueryBuilders.RecordSetter;
using SqExpress.GetStarted;
using SqExpress.Syntax.Names;
using System.Collections.Generic;
using SqExpress.Syntax.Select.SelectItems;

namespace SqExpress.GetStarted.Models
{
    public class CustomerData
    {
        //Auto-generated by SqExpress Code-gen util
        public CustomerData(int id, short customerType, string name)
        {
            this.Id = id;
            this.CustomerType = customerType;
            this.Name = name;
        }

        //Auto-generated by SqExpress Code-gen util
        public static CustomerData Read(ISqDataRecordReader record, DerivedTableCustomer table)
        {
            return new CustomerData(id: table.CustomerId.Read(record), customerType: table.Type.Read(record), name: table.Name.Read(record));
        }

        //Auto-generated by SqExpress Code-gen util
        public static CustomerData ReadWithPrefix(ISqDataRecordReader record, DerivedTableCustomer table, string prefix)
        {
            return new CustomerData(id: table.CustomerId.Read(record, prefix + table.CustomerId.ColumnName.Name), customerType: table.Type.Read(record, prefix + table.Type.ColumnName.Name), name: table.Name.Read(record, prefix + table.Name.ColumnName.Name));
        }

        //Auto-generated by SqExpress Code-gen util
        public static CustomerData ReadOrdinal(ISqDataRecordReader record, DerivedTableCustomer table, int offset)
        {
            return new CustomerData(id: table.CustomerId.Read(record, offset), customerType: table.Type.Read(record, offset + 1), name: table.Name.Read(record, offset + 2));
        }

        //Auto-generated by SqExpress Code-gen util
        public int Id { get; }

        //Auto-generated by SqExpress Code-gen util
        public short CustomerType { get; }

        //Auto-generated by SqExpress Code-gen util
        public string Name { get; }

        //Auto-generated by SqExpress Code-gen util
        public CustomerData WithId(int id)
        {
            return new CustomerData(id: id, customerType: this.CustomerType, name: this.Name);
        }

        //Auto-generated by SqExpress Code-gen util
        public CustomerData WithCustomerType(short customerType)
        {
            return new CustomerData(id: this.Id, customerType: customerType, name: this.Name);
        }

        //Auto-generated by SqExpress Code-gen util
        public CustomerData WithName(string name)
        {
            return new CustomerData(id: this.Id, customerType: this.CustomerType, name: name);
        }

        //Auto-generated by SqExpress Code-gen util
        public static ExprColumn[] GetColumns(DerivedTableCustomer table)
        {
            return new ExprColumn[]{table.CustomerId, table.Type, table.Name};
        }

        //Auto-generated by SqExpress Code-gen util
        public static ExprAliasedColumn[] GetColumnsWithPrefix(DerivedTableCustomer table, string prefix)
        {
            return new ExprAliasedColumn[]{table.CustomerId.As(prefix + table.CustomerId.ColumnName.Name), table.Type.As(prefix + table.Type.ColumnName.Name), table.Name.As(prefix + table.Name.ColumnName.Name)};
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNull(ISqDataRecordReader record, DerivedTableCustomer table)
        {
            foreach (var column in GetColumns(table))
            {
                if (!record.IsDBNull(column.ColumnName.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNullWithPrefix(ISqDataRecordReader record, DerivedTableCustomer table, string prefix)
        {
            foreach (var column in GetColumnsWithPrefix(table, prefix))
            {
                if (!record.IsDBNull(column.Alias!.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelReader<CustomerData, DerivedTableCustomer> GetReader()
        {
            return CustomerDataReader.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class CustomerDataReader : ISqModelReader<CustomerData, DerivedTableCustomer>
        {
            public static CustomerDataReader Instance { get; } = new CustomerDataReader();
            IReadOnlyList<ExprColumn> ISqModelReader<CustomerData, DerivedTableCustomer>.GetColumns(DerivedTableCustomer table)
            {
                return CustomerData.GetColumns(table);
            }

            CustomerData ISqModelReader<CustomerData, DerivedTableCustomer>.Read(ISqDataRecordReader record, DerivedTableCustomer table)
            {
                return CustomerData.Read(record, table);
            }

            CustomerData ISqModelReader<CustomerData, DerivedTableCustomer>.ReadOrdinal(ISqDataRecordReader record, DerivedTableCustomer table, int offset)
            {
                return CustomerData.ReadOrdinal(record, table, offset);
            }
        }
    }
}