using System;
using SqExpress;
using SqExpress.QueryBuilders.RecordSetter;
using SqExpress.GetStarted;
using SqExpress.Syntax.Names;
using System.Collections.Generic;
using SqExpress.Syntax.Select.SelectItems;

namespace SqExpress.GetStarted.Models
{
    public class UserName
    {
        //Auto-generated by SqExpress Code-gen util
        public UserName(int id, string firstName, string lastName)
        {
            this.Id = id;
            this.FirstName = firstName;
            this.LastName = lastName;
        }

        //Auto-generated by SqExpress Code-gen util
        public static UserName Read(ISqDataRecordReader record, TableUser table)
        {
            return new UserName(id: table.UserId.Read(record), firstName: table.FirstName.Read(record), lastName: table.LastName.Read(record));
        }

        //Auto-generated by SqExpress Code-gen util
        public static UserName ReadWithPrefix(ISqDataRecordReader record, TableUser table, string prefix)
        {
            return new UserName(id: table.UserId.Read(record, prefix + table.UserId.ColumnName.Name), firstName: table.FirstName.Read(record, prefix + table.FirstName.ColumnName.Name), lastName: table.LastName.Read(record, prefix + table.LastName.ColumnName.Name));
        }

        //Auto-generated by SqExpress Code-gen util
        public static UserName ReadOrdinal(ISqDataRecordReader record, TableUser table, int offset)
        {
            return new UserName(id: table.UserId.Read(record, offset), firstName: table.FirstName.Read(record, offset + 1), lastName: table.LastName.Read(record, offset + 2));
        }

        //Auto-generated by SqExpress Code-gen util
        public int Id { get; }

        //Auto-generated by SqExpress Code-gen util
        public string FirstName { get; }

        //Auto-generated by SqExpress Code-gen util
        public string LastName { get; }

        //Auto-generated by SqExpress Code-gen util
        public UserName WithId(int id)
        {
            return new UserName(id: id, firstName: this.FirstName, lastName: this.LastName);
        }

        //Auto-generated by SqExpress Code-gen util
        public UserName WithFirstName(string firstName)
        {
            return new UserName(id: this.Id, firstName: firstName, lastName: this.LastName);
        }

        //Auto-generated by SqExpress Code-gen util
        public UserName WithLastName(string lastName)
        {
            return new UserName(id: this.Id, firstName: this.FirstName, lastName: lastName);
        }

        //Auto-generated by SqExpress Code-gen util
        public static TableColumn[] GetColumns(TableUser table)
        {
            return new TableColumn[]{table.UserId, table.FirstName, table.LastName};
        }

        //Auto-generated by SqExpress Code-gen util
        public static ExprAliasedColumn[] GetColumnsWithPrefix(TableUser table, string prefix)
        {
            return new ExprAliasedColumn[]{table.UserId.As(prefix + table.UserId.ColumnName.Name), table.FirstName.As(prefix + table.FirstName.ColumnName.Name), table.LastName.As(prefix + table.LastName.ColumnName.Name)};
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNull(ISqDataRecordReader record, TableUser table)
        {
            foreach (var column in GetColumns(table))
            {
                if (!record.IsDBNull(column.ColumnName.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNullWithPrefix(ISqDataRecordReader record, TableUser table, string prefix)
        {
            foreach (var column in GetColumnsWithPrefix(table, prefix))
            {
                if (!record.IsDBNull(column.Alias.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetMapping(IDataMapSetter<TableUser, UserName> s)
        {
            return s.Set(s.Target.FirstName, s.Source.FirstName).Set(s.Target.LastName, s.Source.LastName);
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetUpdateKeyMapping(IDataMapSetter<TableUser, UserName> s)
        {
            return s.Set(s.Target.UserId, s.Source.Id);
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetUpdateMapping(IDataMapSetter<TableUser, UserName> s)
        {
            return s.Set(s.Target.FirstName, s.Source.FirstName).Set(s.Target.LastName, s.Source.LastName);
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelReader<UserName, TableUser> GetReader()
        {
            return UserNameReader.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class UserNameReader : ISqModelReader<UserName, TableUser>
        {
            public static UserNameReader Instance { get; } = new UserNameReader();
            IReadOnlyList<ExprColumn> ISqModelReader<UserName, TableUser>.GetColumns(TableUser table)
            {
                return UserName.GetColumns(table);
            }

            UserName ISqModelReader<UserName, TableUser>.Read(ISqDataRecordReader record, TableUser table)
            {
                return UserName.Read(record, table);
            }

            UserName ISqModelReader<UserName, TableUser>.ReadOrdinal(ISqDataRecordReader record, TableUser table, int offset)
            {
                return UserName.ReadOrdinal(record, table, offset);
            }
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelUpdaterKey<UserName, TableUser> GetUpdater()
        {
            return UserNameUpdater.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class UserNameUpdater : ISqModelUpdaterKey<UserName, TableUser>
        {
            public static UserNameUpdater Instance { get; } = new UserNameUpdater();
            IRecordSetterNext ISqModelUpdater<UserName, TableUser>.GetMapping(IDataMapSetter<TableUser, UserName> dataMapSetter)
            {
                return UserName.GetMapping(dataMapSetter);
            }

            IRecordSetterNext ISqModelUpdaterKey<UserName, TableUser>.GetUpdateKeyMapping(IDataMapSetter<TableUser, UserName> dataMapSetter)
            {
                return UserName.GetUpdateKeyMapping(dataMapSetter);
            }

            IRecordSetterNext ISqModelUpdaterKey<UserName, TableUser>.GetUpdateMapping(IDataMapSetter<TableUser, UserName> dataMapSetter)
            {
                return UserName.GetUpdateMapping(dataMapSetter);
            }
        }
    }
}