using System.Text;
using System.Text.Json;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using SourceGenerator = SqExpress.GenSyntaxTraversal.Program;
using NodeModel = SqExpress.GenSyntaxTraversal.NodeModel;
using PropertyModel = SqExpress.GenSyntaxTraversal.SubNodeModel;

if (args.Length is < 2 or > 3 || (args.Length == 3 && args[2] != "--check")) { Console.Error.WriteLine("Usage: Sqyra.CodeGen <SqExpress path> <output directory> [--check]"); return 2; }
var sourceRoot = Path.GetFullPath(args[0]); var outputRoot = Path.GetFullPath(args[1]); var check = args.Length == 3;
if (!Directory.Exists(Path.Combine(sourceRoot, "Syntax"))) { Console.Error.WriteLine($"SqExpress syntax directory was not found: {sourceRoot}"); return 2; }
IReadOnlyList<NodeModel> models;
try { models = SourceGenerator.BuildModelRoslyn(sourceRoot); }
catch (Exception error) { Console.Error.WriteLine($"Semantic AST discovery failed: {error}"); return 3; }

var concrete = models.Where(m => !m.IsAbstract && !m.IsInterface && m.TypeName.StartsWith("Expr", StringComparison.Ordinal)).ToArray();
var categories = models.Where(m => m.IsAbstract || m.IsInterface).ToArray();
var enums = ReadEnums(Path.Combine(sourceRoot, "Syntax"));
var directBases = ReadBaseTypes(sourceRoot, models.Select(m => m.TypeName).Append("IExpr").ToHashSet(StringComparer.Ordinal));
var known = models.Select(m => m.TypeName).Concat(enums.Keys).ToHashSet(StringComparer.Ordinal);
var unknown = models.SelectMany(m => m.Properties).Select(p => p.PropertyType).Where(t => !known.Contains(t) && !IsPrimitive(t)).Distinct().OrderBy(t => t).ToArray();
if (unknown.Length > 0) { Console.Error.WriteLine($"Unsupported AST property types: {string.Join(", ", unknown)}"); return 4; }
var output = Render(models, concrete, categories, enums, directBases);
var modelOutput = JsonSerializer.Serialize(models.Select(m => new { name = m.TypeName, kind = m.Kind.ToString(), bases = directBases.GetValueOrDefault(m.TypeName, []), customTraversal = m.IsCustomTraversal, fields = m.SubNodes.Select(p => ModelField(p, true)).Concat(m.Properties.Select(p => ModelField(p, false))) }), new JsonSerializerOptions { WriteIndented = true, PropertyNamingPolicy = JsonNamingPolicy.CamelCase }) + "\n";
Directory.CreateDirectory(outputRoot); var outputPath = Path.Combine(outputRoot, "ast.generated.ts"); var modelPath = Path.Combine(outputRoot, "ast-model.generated.json");
if (check) { if (!File.Exists(outputPath) || File.ReadAllText(outputPath) != output || !File.Exists(modelPath) || File.ReadAllText(modelPath) != modelOutput) { Console.Error.WriteLine("Generated AST output is stale. Run npm run codegen."); return 1; } }
else { File.WriteAllText(outputPath, output); File.WriteAllText(modelPath, modelOutput); Console.WriteLine($"Generated {concrete.Length} concrete nodes and {categories.Length} semantic categories."); }
return 0;

static string Render(IReadOnlyList<NodeModel> all, IReadOnlyList<NodeModel> concrete, IReadOnlyList<NodeModel> categories, IReadOnlyDictionary<string, string[]> enums, IReadOnlyDictionary<string, string[]> directBases)
{
    var b = new StringBuilder("// <auto-generated />\n// Generated from SqExpress semantic symbols. Do not edit.\n\n");
    b.AppendLine("import { freezeNode } from \"../runtime.js\";"); b.AppendLine("import type { AstNodeBase, DecimalPrecisionScale, DecimalValue, DateTimeValue, DateTimeOffsetValue, GuidValue } from \"../runtime.js\";\n");
    foreach (var item in enums.OrderBy(e => e.Key)) b.AppendLine($"export type {item.Key} = {string.Join(" | ", item.Value.Select(v => $"\"{v}\""))};");
    if (enums.Count > 0) b.AppendLine();
    foreach (var node in concrete) {
        b.AppendLine($"export interface {node.TypeName} extends AstNodeBase<\"{node.TypeName}\"> {{");
        foreach (var p in node.SubNodes.Concat(node.Properties)) b.AppendLine($"  readonly {Camel(p.PropertyName)}: {TsType(p, all)};");
        b.AppendLine("}\n");
    }
    foreach (var category in categories) {
        var members = concrete.Where(c => IsDescendant(c.TypeName, category.TypeName, directBases)).Select(c => c.TypeName).ToArray();
        if (members.Length == 0) throw new InvalidOperationException($"AST category {category.TypeName} has no concrete descendants.");
        b.AppendLine($"export type {category.TypeName} = {string.Join(" | ", members)};");
    }
    b.AppendLine($"\nexport type Expr = {string.Join(" | ", concrete.Select(c => c.TypeName))};"); b.AppendLine("export type AstKind = Expr[\"kind\"];\n");
    foreach (var node in concrete) {
        var nodeFields = node.SubNodes.Concat(node.Properties).ToArray();
        var fields = nodeFields.Length > 0 ? $"fields: Omit<{node.TypeName}, \"kind\">" : "";
        var expectedFields = $"[{string.Join(", ", nodeFields.Select(p => $"\"{Camel(p.PropertyName)}\""))}]";
        var call = fields.Length > 0 ? $"freezeNode(\"{node.TypeName}\", fields, {expectedFields})" : $"freezeNode(\"{node.TypeName}\", {{}}, {expectedFields})";
        if (node.IsSingleton) b.AppendLine($"export const {Camel(node.TypeName)}: {node.TypeName} = {call};"); else b.AppendLine($"export function {Camel(node.TypeName)}({fields}): {node.TypeName} {{ return {call}; }}");
    }
    b.AppendLine("\nexport interface AstVisitor<R, C = void> {"); foreach (var node in concrete) b.AppendLine($"  readonly {node.TypeName}: (node: {node.TypeName}, context: C) => R;"); b.AppendLine("}\n");
    b.AppendLine("export function visitNode<R, C>(visitor: AstVisitor<R, C>, node: Expr, context: C): R {\n  switch (node.kind) {"); foreach (var node in concrete) b.AppendLine($"    case \"{node.TypeName}\": return visitor.{node.TypeName}(node, context);"); b.AppendLine("  }\n}\n");
    b.AppendLine("export interface ChildField { readonly name: string; readonly expectedType: string; readonly collection: boolean; readonly nullable: boolean; }"); b.AppendLine("export const childFields: { readonly [K in AstKind]: ReadonlyArray<ChildField> } = {");
    foreach (var node in concrete) b.AppendLine($"  {node.TypeName}: [{string.Join(", ", node.SubNodes.Select(p => $"{{ name: \"{Camel(p.PropertyName)}\", expectedType: \"{p.PropertyType}\", collection: {p.IsList.ToString().ToLowerInvariant()}, nullable: {p.IsNullable.ToString().ToLowerInvariant()} }}"))}],");
    b.AppendLine("};\n");
    b.AppendLine("export interface NodeField { readonly name: string; readonly expectedType: string; readonly child: boolean; readonly collection: boolean; readonly nullable: boolean; }");
    b.AppendLine("export const nodeFields: { readonly [K in AstKind]: ReadonlyArray<NodeField> } = {");
    foreach (var node in concrete) b.AppendLine($"  {node.TypeName}: [{string.Join(", ", node.SubNodes.Select(p => Field(p, true)).Concat(node.Properties.Select(p => Field(p, false))))}],");
    b.AppendLine("};\n");
    b.AppendLine("export const nodeTypeKinds: Readonly<Record<string, ReadonlySet<AstKind>>> = {");
    b.AppendLine($"  IExpr: new Set([{string.Join(", ", concrete.Select(n => $"\"{n.TypeName}\""))}]),");
    foreach (var model in all) { var members = model.IsAbstract || model.IsInterface ? concrete.Where(c => IsDescendant(c.TypeName, model.TypeName, directBases)).Select(c => c.TypeName) : new[] { model.TypeName }; b.AppendLine($"  {model.TypeName}: new Set([{string.Join(", ", members.Select(n => $"\"{n}\""))}]),"); }
    b.AppendLine("};\n");
    b.AppendLine("export const enumValues: Readonly<Record<string, ReadonlySet<string>>> = {");
    foreach (var item in enums.OrderBy(e => e.Key)) b.AppendLine($"  {item.Key}: new Set([{string.Join(", ", item.Value.Select(v => $"\"{v}\""))}]),");
    b.AppendLine("};\n"); b.AppendLine($"const knownKinds: ReadonlySet<string> = nodeTypeKinds.IExpr!;"); b.AppendLine("export function isAstKind(value: string): value is AstKind { return knownKinds.has(value); }"); return b.ToString();
}
static string Field(PropertyModel p, bool child) => $"{{ name: \"{Camel(p.PropertyName)}\", expectedType: \"{p.PropertyType}\", child: {child.ToString().ToLowerInvariant()}, collection: {p.IsList.ToString().ToLowerInvariant()}, nullable: {p.IsNullable.ToString().ToLowerInvariant()} }}";
static object ModelField(PropertyModel p, bool child) => new { name = p.PropertyName, constructorArgument = p.ConstructorArgumentName, type = p.PropertyType, hostType = p.HostTypeName, child, collection = p.IsList, collectionType = p.ListName, nullable = p.IsNullable };
static bool IsDescendant(string node, string category, IReadOnlyDictionary<string, string[]> directBases, HashSet<string>? seen = null) { seen ??= new HashSet<string>(); if (!seen.Add(node) || !directBases.TryGetValue(node, out var bases)) return false; return bases.Contains(category, StringComparer.Ordinal) || bases.Any(parent => IsDescendant(parent, category, directBases, new HashSet<string>(seen))); }
static string TsType(PropertyModel p, IReadOnlyList<NodeModel> all) { var type = p.PropertyType switch { "String" => "string", "Boolean" => "boolean", "Byte" or "Int16" or "Int32" or "Double" => "number", "Int64" => "bigint", "Decimal" => "DecimalValue", "Guid" => "GuidValue", "DateTime" => "DateTimeValue", "DateTimeOffset" => "DateTimeOffsetValue", "DecimalPrecisionScale" => "DecimalPrecisionScale", _ => p.PropertyType }; if (p.IsList) type = p.PropertyType == "Byte" && !all.Any(m => m.TypeName == p.PropertyType) ? "Uint8Array" : $"ReadonlyArray<{type}>"; return p.IsNullable ? $"{type} | null" : type; }
static bool IsPrimitive(string type) => type is "String" or "Boolean" or "Byte" or "Int16" or "Int32" or "Int64" or "Decimal" or "Double" or "Guid" or "DateTime" or "DateTimeOffset" or "DecimalPrecisionScale";
static string Camel(string value) => char.ToLowerInvariant(value[0]) + value[1..];
static Dictionary<string, string[]> ReadEnums(string root) => Directory.EnumerateFiles(root, "*.cs", SearchOption.AllDirectories).SelectMany(path => CSharpSyntaxTree.ParseText(File.ReadAllText(path)).GetRoot().DescendantNodes().OfType<EnumDeclarationSyntax>()).Where(e => e.Modifiers.Any(m => m.Text == "public")).GroupBy(e => e.Identifier.Text).ToDictionary(g => g.Key, g => g.SelectMany(e => e.Members).Select(m => m.Identifier.Text).Distinct().OrderBy(v => v).ToArray());
static Dictionary<string, string[]> ReadBaseTypes(string root, HashSet<string> known) => Directory.EnumerateFiles(root, "*.cs", SearchOption.AllDirectories).SelectMany(path => CSharpSyntaxTree.ParseText(File.ReadAllText(path)).GetRoot().DescendantNodes().OfType<TypeDeclarationSyntax>()).Where(t => known.Contains(t.Identifier.Text)).GroupBy(t => t.Identifier.Text).ToDictionary(g => g.Key, g => g.SelectMany(t => t.BaseList?.Types ?? []).Select(t => t.Type switch { GenericNameSyntax generic => generic.Identifier.Text, QualifiedNameSyntax qualified => qualified.Right.Identifier.Text, IdentifierNameSyntax identifier => identifier.Identifier.Text, _ => t.Type.ToString().Split('.').Last() }).Where(known.Contains).Distinct().OrderBy(v => v).ToArray());
