using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;
using SqExpress;
using SqExpress.Analyzers.Diagnostics;

namespace SqExpress.Analyzers
{
    public sealed partial class TableDescriptorSourceGenerator
    {
        private static void Execute(SourceProductionContext context, ImmutableArray<TableDescriptorCandidate?> candidates)
        {
            var materializedCandidates = candidates.Where(static c => c != null).Cast<TableDescriptorCandidate>().ToImmutableArray();
            if (materializedCandidates.IsDefaultOrEmpty)
            {
                return;
            }

            foreach (var candidate in materializedCandidates)
            {
                foreach (var diagnostic in candidate.Diagnostics)
                {
                    context.ReportDiagnostic(diagnostic);
                }
            }

            var duplicatesByKey = materializedCandidates
                .GroupBy(static c => c.TableKey, StringComparer.OrdinalIgnoreCase)
                .Where(static g => g.Count() > 1)
                .ToDictionary(static g => g.Key, static g => g.ToImmutableArray(), StringComparer.OrdinalIgnoreCase);

            foreach (var duplicate in duplicatesByKey.Values)
            {
                foreach (var candidate in duplicate)
                {
                    context.ReportDiagnostic(CreateDiagnostic(DiagnosticDescriptors.TableDescriptorDuplicateTable, candidate.Symbol, candidate.TableDisplayName));
                }
            }

            var uniqueTables = materializedCandidates
                .Where(c => !duplicatesByKey.ContainsKey(c.TableKey))
                .ToDictionary(static c => c.TableKey, static c => c, StringComparer.OrdinalIgnoreCase);

            foreach (var candidate in materializedCandidates)
            {
                if (candidate.Diagnostics.Any() || duplicatesByKey.ContainsKey(candidate.TableKey))
                {
                    continue;
                }

                var validation = ValidateCandidate(candidate, uniqueTables);
                foreach (var diagnostic in validation.Diagnostics)
                {
                    context.ReportDiagnostic(diagnostic);
                }

                if (validation.Diagnostics.Length > 0)
                {
                    continue;
                }

                var source = RenderCandidate(candidate, validation.PropertyNamesBySqlName, uniqueTables);
                context.AddSource(GetHintName(candidate), SourceText.From(source, Encoding.UTF8));
            }
        }

        private static string GetHintName(TableDescriptorCandidate candidate)
        {
            var name = candidate.Symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat).Replace("global::", string.Empty);
            return $"{name.Replace('<', '_').Replace('>', '_').Replace('.', '_')}.TableDescriptor.g.cs";
        }

        private static string RenderCandidate(
            TableDescriptorCandidate candidate,
            IReadOnlyDictionary<string, string> propertyNamesBySqlName,
            IReadOnlyDictionary<string, TableDescriptorCandidate> allTables)
        {
            var builder = new StringBuilder();
            builder.AppendLine("// <auto-generated/>");
            builder.AppendLine("#nullable enable");

            if (!candidate.Symbol.ContainingNamespace.IsGlobalNamespace)
            {
                builder.Append("namespace ").Append(candidate.Symbol.ContainingNamespace.ToDisplayString()).AppendLine();
                builder.AppendLine("{");
            }

            builder.Append("partial class ").Append(candidate.Symbol.Name).Append(" : global::SqExpress.TableBase").AppendLine();
            builder.AppendLine("{");
            builder.Append("    public ").Append(candidate.Symbol.Name).AppendLine("() : this(alias: global::SqExpress.Alias.Auto)");
            builder.AppendLine("    {");
            builder.AppendLine("    }");
            builder.AppendLine();

            builder.Append("    public ").Append(candidate.Symbol.Name).Append("(global::SqExpress.Alias alias) : base(").Append(RenderBaseConstructorArguments(candidate)).AppendLine(")");
            builder.AppendLine("    {");

            foreach (var column in candidate.Columns)
            {
                builder.Append("        this.")
                    .Append(propertyNamesBySqlName[column.SqlName])
                    .Append(" = this.")
                    .Append(RenderCreateMethodName(column))
                    .Append("(")
                    .Append(RenderCreateMethodArguments(column, candidate, allTables))
                    .AppendLine(");");
            }

            foreach (var index in candidate.Indexes)
            {
                builder.Append("        this.")
                    .Append(RenderIndexMethodName(index))
                    .Append("(")
                    .Append(RenderIndexArguments(index, propertyNamesBySqlName))
                    .AppendLine(");");
            }

            builder.AppendLine("    }");
            builder.AppendLine();

            foreach (var column in candidate.Columns)
            {
                builder.Append("    public ")
                    .Append(RenderPropertyType(column))
                    .Append(' ')
                    .Append(propertyNamesBySqlName[column.SqlName])
                    .AppendLine(" { get; }");
            }

            builder.AppendLine("}");

            if (!candidate.Symbol.ContainingNamespace.IsGlobalNamespace)
            {
                builder.AppendLine("}");
            }

            return builder.ToString();
        }

        private static string RenderBaseConstructorArguments(TableDescriptorCandidate candidate)
        {
            if (!string.IsNullOrEmpty(candidate.DatabaseName))
            {
                return $"{Literal(candidate.DatabaseName)}, {Literal(candidate.SchemaName)}, {Literal(candidate.TableName)}, alias";
            }

            return candidate.SchemaName != null
                ? $"{Literal(candidate.SchemaName)}, {Literal(candidate.TableName)}, alias"
                : $"null, {Literal(candidate.TableName)}, alias";
        }

        private static string RenderCreateMethodArguments(
            ColumnDescriptor column,
            TableDescriptorCandidate candidate,
            IReadOnlyDictionary<string, TableDescriptorCandidate> allTables)
        {
            var columnMeta = RenderColumnMeta(column, candidate, allTables);
            return column.Kind switch
            {
                ColumnKind.String or ColumnKind.NullableString => $"name: {Literal(column.SqlName)}, size: {RenderNullableInt(column.MaxLength)}, isUnicode: {RenderBool(column.IsUnicode)}, isText: {RenderBool(column.IsText)}, columnMeta: {columnMeta}",
                ColumnKind.ByteArray or ColumnKind.NullableByteArray => $"{Literal(column.SqlName)}, {RenderNullableInt(column.MaxLength)}, {columnMeta}",
                ColumnKind.Decimal or ColumnKind.NullableDecimal => $"{Literal(column.SqlName)}, new global::SqExpress.Syntax.Type.DecimalPrecisionScale(precision: {column.Precision}, scale: {column.Scale}), {columnMeta}",
                ColumnKind.DateTime or ColumnKind.NullableDateTime => $"{Literal(column.SqlName)}, {RenderBool(column.IsDate)}, {columnMeta}",
                _ => $"{Literal(column.SqlName)}, {columnMeta}"
            };
        }

        private static string RenderColumnMeta(
            ColumnDescriptor column,
            TableDescriptorCandidate candidate,
            IReadOnlyDictionary<string, TableDescriptorCandidate> allTables)
        {
            var current = string.Empty;

            void Append(string fragment)
            {
                current = string.IsNullOrEmpty(current)
                    ? $"global::SqExpress.ColumnMeta.{fragment}"
                    : $"{current}.{fragment}";
            }

            if (column.IsPrimaryKey)
            {
                Append("PrimaryKey()");
            }

            if (column.IsIdentity)
            {
                Append("Identity()");
            }

            if (column.DefaultValueKind != TableColumnDefaultValueKind.None)
            {
                Append($"DefaultValue({RenderDefaultValue(column)})");
            }

            if (!string.IsNullOrWhiteSpace(column.ForeignKeyTable) && !string.IsNullOrWhiteSpace(column.ForeignKeyColumn))
            {
                var targetKey = BuildTableKey(column.ForeignKeyDatabase, column.ForeignKeySchema ?? candidate.SchemaName, column.ForeignKeyTable!);
                if (allTables.TryGetValue(targetKey, out var targetTable))
                {
                    var targetPropertyName = targetTable.Columns
                        .Where(c => string.Equals(c.SqlName, column.ForeignKeyColumn, StringComparison.OrdinalIgnoreCase))
                        .Select(c => string.IsNullOrWhiteSpace(c.PropertyName) ? ToIdentifier(c.SqlName) : c.PropertyName!)
                        .First();

                    Append($"ForeignKey<{targetTable.Symbol.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)}>(t => t.{targetPropertyName})");
                }
            }

            return string.IsNullOrEmpty(current) ? "null" : current;
        }

        private static string RenderDefaultValue(ColumnDescriptor column)
        {
            return column.DefaultValueKind switch
            {
                TableColumnDefaultValueKind.Raw => $"global::SqExpress.SqQueryBuilder.UnsafeValue({Literal(column.DefaultValue ?? string.Empty)})",
                TableColumnDefaultValueKind.Null => "global::SqExpress.SqQueryBuilder.Null",
                TableColumnDefaultValueKind.Integer => column.DefaultValue ?? "0",
                TableColumnDefaultValueKind.Bool => bool.TryParse(column.DefaultValue, out var boolValue) ? RenderBool(boolValue) : "false",
                TableColumnDefaultValueKind.String => Literal(column.DefaultValue ?? string.Empty),
                TableColumnDefaultValueKind.GetUtcDate => "global::SqExpress.SqQueryBuilder.GetUtcDate()",
                _ => "global::SqExpress.SqQueryBuilder.Null"
            };
        }

        private static string RenderIndexMethodName(IndexDescriptor index)
        {
            if (index.IsUnique)
            {
                return index.IsClustered ? "AddUniqueClusteredIndex" : "AddUniqueIndex";
            }

            return index.IsClustered ? "AddClusteredIndex" : "AddIndex";
        }

        private static string RenderIndexArguments(IndexDescriptor index, IReadOnlyDictionary<string, string> propertyNamesBySqlName)
        {
            var parts = new List<string>();
            if (!string.IsNullOrWhiteSpace(index.Name))
            {
                parts.Add(Literal(index.Name));
            }

            foreach (var column in index.Columns)
            {
                parts.Add(index.DescendingColumns.Contains(column, StringComparer.OrdinalIgnoreCase)
                    ? $"global::SqExpress.IndexMetaColumn.Desc(this.{propertyNamesBySqlName[column]})"
                    : $"this.{propertyNamesBySqlName[column]}");
            }

            return string.Join(", ", parts);
        }

        private static string RenderPropertyType(ColumnDescriptor column)
        {
            return column.Kind switch
            {
                ColumnKind.Boolean => "global::SqExpress.BooleanTableColumn",
                ColumnKind.NullableBoolean => "global::SqExpress.NullableBooleanTableColumn",
                ColumnKind.Byte => "global::SqExpress.ByteTableColumn",
                ColumnKind.NullableByte => "global::SqExpress.NullableByteTableColumn",
                ColumnKind.ByteArray => "global::SqExpress.ByteArrayTableColumn",
                ColumnKind.NullableByteArray => "global::SqExpress.NullableByteArrayTableColumn",
                ColumnKind.Int16 => "global::SqExpress.Int16TableColumn",
                ColumnKind.NullableInt16 => "global::SqExpress.NullableInt16TableColumn",
                ColumnKind.Int32 => "global::SqExpress.Int32TableColumn",
                ColumnKind.NullableInt32 => "global::SqExpress.NullableInt32TableColumn",
                ColumnKind.Int64 => "global::SqExpress.Int64TableColumn",
                ColumnKind.NullableInt64 => "global::SqExpress.NullableInt64TableColumn",
                ColumnKind.Double => "global::SqExpress.DoubleTableColumn",
                ColumnKind.NullableDouble => "global::SqExpress.NullableDoubleTableColumn",
                ColumnKind.Decimal => "global::SqExpress.DecimalTableColumn",
                ColumnKind.NullableDecimal => "global::SqExpress.NullableDecimalTableColumn",
                ColumnKind.DateTime => "global::SqExpress.DateTimeTableColumn",
                ColumnKind.NullableDateTime => "global::SqExpress.NullableDateTimeTableColumn",
                ColumnKind.DateTimeOffset => "global::SqExpress.DateTimeOffsetTableColumn",
                ColumnKind.NullableDateTimeOffset => "global::SqExpress.NullableDateTimeOffsetTableColumn",
                ColumnKind.Guid => "global::SqExpress.GuidTableColumn",
                ColumnKind.NullableGuid => "global::SqExpress.NullableGuidTableColumn",
                ColumnKind.String => "global::SqExpress.StringTableColumn",
                ColumnKind.NullableString => "global::SqExpress.NullableStringTableColumn",
                ColumnKind.Xml => "global::SqExpress.StringTableColumn",
                ColumnKind.NullableXml => "global::SqExpress.NullableStringTableColumn",
                _ => throw new ArgumentOutOfRangeException(nameof(column.Kind), column.Kind, null)
            };
        }

        private static string RenderCreateMethodName(ColumnDescriptor column)
        {
            return column.Kind switch
            {
                ColumnKind.Boolean => "CreateBooleanColumn",
                ColumnKind.NullableBoolean => "CreateNullableBooleanColumn",
                ColumnKind.Byte => "CreateByteColumn",
                ColumnKind.NullableByte => "CreateNullableByteColumn",
                ColumnKind.ByteArray when column.IsFixedLength => "CreateFixedSizeByteArrayColumn",
                ColumnKind.ByteArray => "CreateByteArrayColumn",
                ColumnKind.NullableByteArray when column.IsFixedLength => "CreateNullableFixedSizeByteArrayColumn",
                ColumnKind.NullableByteArray => "CreateNullableByteArrayColumn",
                ColumnKind.Int16 => "CreateInt16Column",
                ColumnKind.NullableInt16 => "CreateNullableInt16Column",
                ColumnKind.Int32 => "CreateInt32Column",
                ColumnKind.NullableInt32 => "CreateNullableInt32Column",
                ColumnKind.Int64 => "CreateInt64Column",
                ColumnKind.NullableInt64 => "CreateNullableInt64Column",
                ColumnKind.Double => "CreateDoubleColumn",
                ColumnKind.NullableDouble => "CreateNullableDoubleColumn",
                ColumnKind.Decimal => "CreateDecimalColumn",
                ColumnKind.NullableDecimal => "CreateNullableDecimalColumn",
                ColumnKind.DateTime => "CreateDateTimeColumn",
                ColumnKind.NullableDateTime => "CreateNullableDateTimeColumn",
                ColumnKind.DateTimeOffset => "CreateDateTimeOffsetColumn",
                ColumnKind.NullableDateTimeOffset => "CreateNullableDateTimeOffsetColumn",
                ColumnKind.Guid => "CreateGuidColumn",
                ColumnKind.NullableGuid => "CreateNullableGuidColumn",
                ColumnKind.String when column.IsFixedLength => "CreateFixedSizeStringColumn",
                ColumnKind.String => "CreateStringColumn",
                ColumnKind.NullableString when column.IsFixedLength => "CreateNullableFixedSizeStringColumn",
                ColumnKind.NullableString => "CreateNullableStringColumn",
                ColumnKind.Xml => "CreateXmlColumn",
                ColumnKind.NullableXml => "CreateNullableXmlColumn",
                _ => throw new ArgumentOutOfRangeException(nameof(column.Kind), column.Kind, null)
            };
        }
    }
}
