using System;
using SqExpress;
using SqExpress.QueryBuilders.RecordSetter;
using SqExpress.IntTest.Tables;
using SqExpress.Syntax.Names;
using System.Collections.Generic;
using SqExpress.Syntax.Select.SelectItems;

namespace SqExpress.IntTest.Tables.Models
{
    public class Audit
    {
        //Auto-generated by SqExpress Code-gen util
        public Audit(int version, DateTime created, DateTime modified)
        {
            this.Version = version;
            this.Created = created;
            this.Modified = modified;
        }

        //Auto-generated by SqExpress Code-gen util
        public static Audit Read(ISqDataRecordReader record, TableItCompany table)
        {
            return new Audit(version: table.Version.Read(record), created: table.Created.Read(record), modified: table.Modified.Read(record));
        }

        //Auto-generated by SqExpress Code-gen util
        public static Audit Read(ISqDataRecordReader record, TableItUser table)
        {
            return new Audit(version: table.Version.Read(record), created: table.Created.Read(record), modified: table.Modified.Read(record));
        }

        //Auto-generated by SqExpress Code-gen util
        public static Audit ReadWithPrefix(ISqDataRecordReader record, TableItCompany table, string prefix)
        {
            return new Audit(version: table.Version.Read(record, prefix + table.Version.ColumnName.Name), created: table.Created.Read(record, prefix + table.Created.ColumnName.Name), modified: table.Modified.Read(record, prefix + table.Modified.ColumnName.Name));
        }

        //Auto-generated by SqExpress Code-gen util
        public static Audit ReadWithPrefix(ISqDataRecordReader record, TableItUser table, string prefix)
        {
            return new Audit(version: table.Version.Read(record, prefix + table.Version.ColumnName.Name), created: table.Created.Read(record, prefix + table.Created.ColumnName.Name), modified: table.Modified.Read(record, prefix + table.Modified.ColumnName.Name));
        }

        //Auto-generated by SqExpress Code-gen util
        public static Audit ReadOrdinal(ISqDataRecordReader record, TableItCompany table, int offset)
        {
            return new Audit(version: table.Version.Read(record, offset), created: table.Created.Read(record, offset + 1), modified: table.Modified.Read(record, offset + 2));
        }

        //Auto-generated by SqExpress Code-gen util
        public static Audit ReadOrdinal(ISqDataRecordReader record, TableItUser table, int offset)
        {
            return new Audit(version: table.Version.Read(record, offset), created: table.Created.Read(record, offset + 1), modified: table.Modified.Read(record, offset + 2));
        }

        //Auto-generated by SqExpress Code-gen util
        public int Version { get; }

        //Auto-generated by SqExpress Code-gen util
        public DateTime Created { get; }

        //Auto-generated by SqExpress Code-gen util
        public DateTime Modified { get; }

        //Auto-generated by SqExpress Code-gen util
        public Audit WithVersion(int version)
        {
            return new Audit(version: version, created: this.Created, modified: this.Modified);
        }

        //Auto-generated by SqExpress Code-gen util
        public Audit WithCreated(DateTime created)
        {
            return new Audit(version: this.Version, created: created, modified: this.Modified);
        }

        //Auto-generated by SqExpress Code-gen util
        public Audit WithModified(DateTime modified)
        {
            return new Audit(version: this.Version, created: this.Created, modified: modified);
        }

        //Auto-generated by SqExpress Code-gen util
        public static TableColumn[] GetColumns(TableItCompany table)
        {
            return new TableColumn[]{table.Version, table.Created, table.Modified};
        }

        //Auto-generated by SqExpress Code-gen util
        public static TableColumn[] GetColumns(TableItUser table)
        {
            return new TableColumn[]{table.Version, table.Created, table.Modified};
        }

        //Auto-generated by SqExpress Code-gen util
        public static ExprAliasedColumn[] GetColumnsWithPrefix(TableItCompany table, string prefix)
        {
            return new ExprAliasedColumn[]{table.Version.As(prefix + table.Version.ColumnName.Name), table.Created.As(prefix + table.Created.ColumnName.Name), table.Modified.As(prefix + table.Modified.ColumnName.Name)};
        }

        //Auto-generated by SqExpress Code-gen util
        public static ExprAliasedColumn[] GetColumnsWithPrefix(TableItUser table, string prefix)
        {
            return new ExprAliasedColumn[]{table.Version.As(prefix + table.Version.ColumnName.Name), table.Created.As(prefix + table.Created.ColumnName.Name), table.Modified.As(prefix + table.Modified.ColumnName.Name)};
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNull(ISqDataRecordReader record, TableItCompany table)
        {
            foreach (var column in GetColumns(table))
            {
                if (!record.IsDBNull(column.ColumnName.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNull(ISqDataRecordReader record, TableItUser table)
        {
            foreach (var column in GetColumns(table))
            {
                if (!record.IsDBNull(column.ColumnName.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNullWithPrefix(ISqDataRecordReader record, TableItCompany table, string prefix)
        {
            foreach (var column in GetColumnsWithPrefix(table, prefix))
            {
                if (!record.IsDBNull(column.Alias!.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNullWithPrefix(ISqDataRecordReader record, TableItUser table, string prefix)
        {
            foreach (var column in GetColumnsWithPrefix(table, prefix))
            {
                if (!record.IsDBNull(column.Alias!.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetMapping(IDataMapSetter<TableItCompany, Audit> s)
        {
            return s.Set(s.Target.Version, s.Source.Version).Set(s.Target.Created, s.Source.Created).Set(s.Target.Modified, s.Source.Modified);
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetMapping(IDataMapSetter<TableItUser, Audit> s)
        {
            return s.Set(s.Target.Version, s.Source.Version).Set(s.Target.Created, s.Source.Created).Set(s.Target.Modified, s.Source.Modified);
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelReader<Audit, TableItCompany> GetReaderForTableItCompany()
        {
            return AuditReaderForTableItCompany.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class AuditReaderForTableItCompany : ISqModelReader<Audit, TableItCompany>
        {
            public static AuditReaderForTableItCompany Instance { get; } = new AuditReaderForTableItCompany();
            IReadOnlyList<ExprColumn> ISqModelReader<Audit, TableItCompany>.GetColumns(TableItCompany table)
            {
                return Audit.GetColumns(table);
            }

            Audit ISqModelReader<Audit, TableItCompany>.Read(ISqDataRecordReader record, TableItCompany table)
            {
                return Audit.Read(record, table);
            }

            Audit ISqModelReader<Audit, TableItCompany>.ReadOrdinal(ISqDataRecordReader record, TableItCompany table, int offset)
            {
                return Audit.ReadOrdinal(record, table, offset);
            }
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelReader<Audit, TableItUser> GetReaderForTableItUser()
        {
            return AuditReaderForTableItUser.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class AuditReaderForTableItUser : ISqModelReader<Audit, TableItUser>
        {
            public static AuditReaderForTableItUser Instance { get; } = new AuditReaderForTableItUser();
            IReadOnlyList<ExprColumn> ISqModelReader<Audit, TableItUser>.GetColumns(TableItUser table)
            {
                return Audit.GetColumns(table);
            }

            Audit ISqModelReader<Audit, TableItUser>.Read(ISqDataRecordReader record, TableItUser table)
            {
                return Audit.Read(record, table);
            }

            Audit ISqModelReader<Audit, TableItUser>.ReadOrdinal(ISqDataRecordReader record, TableItUser table, int offset)
            {
                return Audit.ReadOrdinal(record, table, offset);
            }
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelUpdater<Audit, TableItCompany> GetUpdaterForTableItCompany()
        {
            return AuditUpdaterForTableItCompany.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class AuditUpdaterForTableItCompany : ISqModelUpdater<Audit, TableItCompany>
        {
            public static AuditUpdaterForTableItCompany Instance { get; } = new AuditUpdaterForTableItCompany();
            IRecordSetterNext ISqModelUpdater<Audit, TableItCompany>.GetMapping(IDataMapSetter<TableItCompany, Audit> dataMapSetter)
            {
                return Audit.GetMapping(dataMapSetter);
            }
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelUpdater<Audit, TableItUser> GetUpdaterForTableItUser()
        {
            return AuditUpdaterForTableItUser.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class AuditUpdaterForTableItUser : ISqModelUpdater<Audit, TableItUser>
        {
            public static AuditUpdaterForTableItUser Instance { get; } = new AuditUpdaterForTableItUser();
            IRecordSetterNext ISqModelUpdater<Audit, TableItUser>.GetMapping(IDataMapSetter<TableItUser, Audit> dataMapSetter)
            {
                return Audit.GetMapping(dataMapSetter);
            }
        }
    }
}