using System;
using SqExpress;
using SqExpress.QueryBuilders.RecordSetter;
using SqExpress.IntTest.Tables.Derived;
using SqExpress.Syntax.Names;
using System.Collections.Generic;
using SqExpress.Syntax.Select.SelectItems;

namespace SqExpress.IntTest.Tables.Models
{
    public class CustomerNameData
    {
        //Auto-generated by SqExpress Code-gen util
        public CustomerNameData(int id, short typeId, string name)
        {
            this.Id = id;
            this.TypeId = typeId;
            this.Name = name;
        }

        //Auto-generated by SqExpress Code-gen util
        public static CustomerNameData Read(ISqDataRecordReader record, CustomerName table)
        {
            return new CustomerNameData(id: table.CustomerId.Read(record), typeId: table.CustomerTypeId.Read(record), name: table.Name.Read(record));
        }

        //Auto-generated by SqExpress Code-gen util
        public static CustomerNameData ReadWithPrefix(ISqDataRecordReader record, CustomerName table, string prefix)
        {
            return new CustomerNameData(id: table.CustomerId.Read(record, prefix + table.CustomerId.ColumnName.Name), typeId: table.CustomerTypeId.Read(record, prefix + table.CustomerTypeId.ColumnName.Name), name: table.Name.Read(record, prefix + table.Name.ColumnName.Name));
        }

        //Auto-generated by SqExpress Code-gen util
        public static CustomerNameData ReadOrdinal(ISqDataRecordReader record, CustomerName table, int offset)
        {
            return new CustomerNameData(id: table.CustomerId.Read(record, offset), typeId: table.CustomerTypeId.Read(record, offset + 1), name: table.Name.Read(record, offset + 2));
        }

        //Auto-generated by SqExpress Code-gen util
        public int Id { get; }

        //Auto-generated by SqExpress Code-gen util
        public short TypeId { get; }

        //Auto-generated by SqExpress Code-gen util
        public string Name { get; }

        //Auto-generated by SqExpress Code-gen util
        public CustomerNameData WithId(int id)
        {
            return new CustomerNameData(id: id, typeId: this.TypeId, name: this.Name);
        }

        //Auto-generated by SqExpress Code-gen util
        public CustomerNameData WithTypeId(short typeId)
        {
            return new CustomerNameData(id: this.Id, typeId: typeId, name: this.Name);
        }

        //Auto-generated by SqExpress Code-gen util
        public CustomerNameData WithName(string name)
        {
            return new CustomerNameData(id: this.Id, typeId: this.TypeId, name: name);
        }

        //Auto-generated by SqExpress Code-gen util
        public static ExprColumn[] GetColumns(CustomerName table)
        {
            return new ExprColumn[]{table.CustomerId, table.CustomerTypeId, table.Name};
        }

        //Auto-generated by SqExpress Code-gen util
        public static ExprAliasedColumn[] GetColumnsWithPrefix(CustomerName table, string prefix)
        {
            return new ExprAliasedColumn[]{table.CustomerId.As(prefix + table.CustomerId.ColumnName.Name), table.CustomerTypeId.As(prefix + table.CustomerTypeId.ColumnName.Name), table.Name.As(prefix + table.Name.ColumnName.Name)};
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNull(ISqDataRecordReader record, CustomerName table)
        {
            foreach (var column in GetColumns(table))
            {
                if (!record.IsDBNull(column.ColumnName.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNullWithPrefix(ISqDataRecordReader record, CustomerName table, string prefix)
        {
            foreach (var column in GetColumnsWithPrefix(table, prefix))
            {
                if (!record.IsDBNull(column.Alias!.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelReader<CustomerNameData, CustomerName> GetReader()
        {
            return CustomerNameDataReader.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class CustomerNameDataReader : ISqModelReader<CustomerNameData, CustomerName>
        {
            public static CustomerNameDataReader Instance { get; } = new CustomerNameDataReader();
            IReadOnlyList<ExprColumn> ISqModelReader<CustomerNameData, CustomerName>.GetColumns(CustomerName table)
            {
                return CustomerNameData.GetColumns(table);
            }

            CustomerNameData ISqModelReader<CustomerNameData, CustomerName>.Read(ISqDataRecordReader record, CustomerName table)
            {
                return CustomerNameData.Read(record, table);
            }

            CustomerNameData ISqModelReader<CustomerNameData, CustomerName>.ReadOrdinal(ISqDataRecordReader record, CustomerName table, int offset)
            {
                return CustomerNameData.ReadOrdinal(record, table, offset);
            }
        }
    }
}