using System;
using SqExpress;
using SqExpress.QueryBuilders.RecordSetter;
using SqExpress.IntTest.Tables;
using SqExpress.Syntax.Names;
using System.Collections.Generic;
using SqExpress.Syntax.Select.SelectItems;

namespace SqExpress.IntTest.Tables.Models
{
    public class Customer
    {
        //Auto-generated by SqExpress Code-gen util
        public Customer(int customerId, int? userId, int? companyId)
        {
            this.CustomerId = customerId;
            this.UserId = userId;
            this.CompanyId = companyId;
        }

        //Auto-generated by SqExpress Code-gen util
        public static Customer Read(ISqDataRecordReader record, TableItCustomer table)
        {
            return new Customer(customerId: table.CustomerId.Read(record), userId: table.UserId.Read(record), companyId: table.CompanyId.Read(record));
        }

        //Auto-generated by SqExpress Code-gen util
        public static Customer ReadWithPrefix(ISqDataRecordReader record, TableItCustomer table, string prefix)
        {
            return new Customer(customerId: table.CustomerId.Read(record, prefix + table.CustomerId.ColumnName.Name), userId: table.UserId.Read(record, prefix + table.UserId.ColumnName.Name), companyId: table.CompanyId.Read(record, prefix + table.CompanyId.ColumnName.Name));
        }

        //Auto-generated by SqExpress Code-gen util
        public static Customer ReadOrdinal(ISqDataRecordReader record, TableItCustomer table, int offset)
        {
            return new Customer(customerId: table.CustomerId.Read(record, offset), userId: table.UserId.Read(record, offset + 1), companyId: table.CompanyId.Read(record, offset + 2));
        }

        //Auto-generated by SqExpress Code-gen util
        public int CustomerId { get; }

        //Auto-generated by SqExpress Code-gen util
        public int? UserId { get; }

        //Auto-generated by SqExpress Code-gen util
        public int? CompanyId { get; }

        //Auto-generated by SqExpress Code-gen util
        public Customer WithCustomerId(int customerId)
        {
            return new Customer(customerId: customerId, userId: this.UserId, companyId: this.CompanyId);
        }

        //Auto-generated by SqExpress Code-gen util
        public Customer WithUserId(int? userId)
        {
            return new Customer(customerId: this.CustomerId, userId: userId, companyId: this.CompanyId);
        }

        //Auto-generated by SqExpress Code-gen util
        public Customer WithCompanyId(int? companyId)
        {
            return new Customer(customerId: this.CustomerId, userId: this.UserId, companyId: companyId);
        }

        //Auto-generated by SqExpress Code-gen util
        public static TableColumn[] GetColumns(TableItCustomer table)
        {
            return new TableColumn[]{table.CustomerId, table.UserId, table.CompanyId};
        }

        //Auto-generated by SqExpress Code-gen util
        public static ExprAliasedColumn[] GetColumnsWithPrefix(TableItCustomer table, string prefix)
        {
            return new ExprAliasedColumn[]{table.CustomerId.As(prefix + table.CustomerId.ColumnName.Name), table.UserId.As(prefix + table.UserId.ColumnName.Name), table.CompanyId.As(prefix + table.CompanyId.ColumnName.Name)};
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNull(ISqDataRecordReader record, TableItCustomer table)
        {
            foreach (var column in GetColumns(table))
            {
                if (!record.IsDBNull(column.ColumnName.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNullWithPrefix(ISqDataRecordReader record, TableItCustomer table, string prefix)
        {
            foreach (var column in GetColumnsWithPrefix(table, prefix))
            {
                if (!record.IsDBNull(column.Alias!.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetMapping(IDataMapSetter<TableItCustomer, Customer> s)
        {
            return s.Set(s.Target.UserId, s.Source.UserId).Set(s.Target.CompanyId, s.Source.CompanyId);
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetUpdateKeyMapping(IDataMapSetter<TableItCustomer, Customer> s)
        {
            return s.Set(s.Target.CustomerId, s.Source.CustomerId);
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetUpdateMapping(IDataMapSetter<TableItCustomer, Customer> s)
        {
            return s.Set(s.Target.UserId, s.Source.UserId).Set(s.Target.CompanyId, s.Source.CompanyId);
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelReader<Customer, TableItCustomer> GetReader()
        {
            return CustomerReader.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class CustomerReader : ISqModelReader<Customer, TableItCustomer>
        {
            public static CustomerReader Instance { get; } = new CustomerReader();
            IReadOnlyList<ExprColumn> ISqModelReader<Customer, TableItCustomer>.GetColumns(TableItCustomer table)
            {
                return Customer.GetColumns(table);
            }

            Customer ISqModelReader<Customer, TableItCustomer>.Read(ISqDataRecordReader record, TableItCustomer table)
            {
                return Customer.Read(record, table);
            }

            Customer ISqModelReader<Customer, TableItCustomer>.ReadOrdinal(ISqDataRecordReader record, TableItCustomer table, int offset)
            {
                return Customer.ReadOrdinal(record, table, offset);
            }
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelUpdaterKey<Customer, TableItCustomer> GetUpdater()
        {
            return CustomerUpdater.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class CustomerUpdater : ISqModelUpdaterKey<Customer, TableItCustomer>
        {
            public static CustomerUpdater Instance { get; } = new CustomerUpdater();
            IRecordSetterNext ISqModelUpdater<Customer, TableItCustomer>.GetMapping(IDataMapSetter<TableItCustomer, Customer> dataMapSetter)
            {
                return Customer.GetMapping(dataMapSetter);
            }

            IRecordSetterNext ISqModelUpdaterKey<Customer, TableItCustomer>.GetUpdateKeyMapping(IDataMapSetter<TableItCustomer, Customer> dataMapSetter)
            {
                return Customer.GetUpdateKeyMapping(dataMapSetter);
            }

            IRecordSetterNext ISqModelUpdaterKey<Customer, TableItCustomer>.GetUpdateMapping(IDataMapSetter<TableItCustomer, Customer> dataMapSetter)
            {
                return Customer.GetUpdateMapping(dataMapSetter);
            }
        }
    }
}