using System;
using SqExpress;
using SqExpress.QueryBuilders.RecordSetter;
using SqExpress.IntTest.Tables;
using SqExpress.Syntax.Names;
using System.Collections.Generic;
using SqExpress.Syntax.Select.SelectItems;

namespace SqExpress.IntTest.Tables.Models
{
    public class OrderDateCreated
    {
        //Auto-generated by SqExpress Code-gen util
        public OrderDateCreated(int orderId, DateTime dateCreated)
        {
            this.OrderId = orderId;
            this.DateCreated = dateCreated;
        }

        //Auto-generated by SqExpress Code-gen util
        public static OrderDateCreated Read(ISqDataRecordReader record, TableItOrder table)
        {
            return new OrderDateCreated(orderId: table.OrderId.Read(record), dateCreated: table.DateCreated.Read(record));
        }

        //Auto-generated by SqExpress Code-gen util
        public static OrderDateCreated ReadWithPrefix(ISqDataRecordReader record, TableItOrder table, string prefix)
        {
            return new OrderDateCreated(orderId: table.OrderId.Read(record, prefix + table.OrderId.ColumnName.Name), dateCreated: table.DateCreated.Read(record, prefix + table.DateCreated.ColumnName.Name));
        }

        //Auto-generated by SqExpress Code-gen util
        public static OrderDateCreated ReadOrdinal(ISqDataRecordReader record, TableItOrder table, int offset)
        {
            return new OrderDateCreated(orderId: table.OrderId.Read(record, offset), dateCreated: table.DateCreated.Read(record, offset + 1));
        }

        //Auto-generated by SqExpress Code-gen util
        public int OrderId { get; }

        //Auto-generated by SqExpress Code-gen util
        public DateTime DateCreated { get; }

        //Auto-generated by SqExpress Code-gen util
        public OrderDateCreated WithOrderId(int orderId)
        {
            return new OrderDateCreated(orderId: orderId, dateCreated: this.DateCreated);
        }

        //Auto-generated by SqExpress Code-gen util
        public OrderDateCreated WithDateCreated(DateTime dateCreated)
        {
            return new OrderDateCreated(orderId: this.OrderId, dateCreated: dateCreated);
        }

        //Auto-generated by SqExpress Code-gen util
        public static TableColumn[] GetColumns(TableItOrder table)
        {
            return new TableColumn[]{table.OrderId, table.DateCreated};
        }

        //Auto-generated by SqExpress Code-gen util
        public static ExprAliasedColumn[] GetColumnsWithPrefix(TableItOrder table, string prefix)
        {
            return new ExprAliasedColumn[]{table.OrderId.As(prefix + table.OrderId.ColumnName.Name), table.DateCreated.As(prefix + table.DateCreated.ColumnName.Name)};
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNull(ISqDataRecordReader record, TableItOrder table)
        {
            foreach (var column in GetColumns(table))
            {
                if (!record.IsDBNull(column.ColumnName.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNullWithPrefix(ISqDataRecordReader record, TableItOrder table, string prefix)
        {
            foreach (var column in GetColumnsWithPrefix(table, prefix))
            {
                if (!record.IsDBNull(column.Alias!.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetMapping(IDataMapSetter<TableItOrder, OrderDateCreated> s)
        {
            return s.Set(s.Target.DateCreated, s.Source.DateCreated);
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetUpdateKeyMapping(IDataMapSetter<TableItOrder, OrderDateCreated> s)
        {
            return s.Set(s.Target.OrderId, s.Source.OrderId);
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetUpdateMapping(IDataMapSetter<TableItOrder, OrderDateCreated> s)
        {
            return s.Set(s.Target.DateCreated, s.Source.DateCreated);
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelReader<OrderDateCreated, TableItOrder> GetReader()
        {
            return OrderDateCreatedReader.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class OrderDateCreatedReader : ISqModelReader<OrderDateCreated, TableItOrder>
        {
            public static OrderDateCreatedReader Instance { get; } = new OrderDateCreatedReader();
            IReadOnlyList<ExprColumn> ISqModelReader<OrderDateCreated, TableItOrder>.GetColumns(TableItOrder table)
            {
                return OrderDateCreated.GetColumns(table);
            }

            OrderDateCreated ISqModelReader<OrderDateCreated, TableItOrder>.Read(ISqDataRecordReader record, TableItOrder table)
            {
                return OrderDateCreated.Read(record, table);
            }

            OrderDateCreated ISqModelReader<OrderDateCreated, TableItOrder>.ReadOrdinal(ISqDataRecordReader record, TableItOrder table, int offset)
            {
                return OrderDateCreated.ReadOrdinal(record, table, offset);
            }
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelUpdaterKey<OrderDateCreated, TableItOrder> GetUpdater()
        {
            return OrderDateCreatedUpdater.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class OrderDateCreatedUpdater : ISqModelUpdaterKey<OrderDateCreated, TableItOrder>
        {
            public static OrderDateCreatedUpdater Instance { get; } = new OrderDateCreatedUpdater();
            IRecordSetterNext ISqModelUpdater<OrderDateCreated, TableItOrder>.GetMapping(IDataMapSetter<TableItOrder, OrderDateCreated> dataMapSetter)
            {
                return OrderDateCreated.GetMapping(dataMapSetter);
            }

            IRecordSetterNext ISqModelUpdaterKey<OrderDateCreated, TableItOrder>.GetUpdateKeyMapping(IDataMapSetter<TableItOrder, OrderDateCreated> dataMapSetter)
            {
                return OrderDateCreated.GetUpdateKeyMapping(dataMapSetter);
            }

            IRecordSetterNext ISqModelUpdaterKey<OrderDateCreated, TableItOrder>.GetUpdateMapping(IDataMapSetter<TableItOrder, OrderDateCreated> dataMapSetter)
            {
                return OrderDateCreated.GetUpdateMapping(dataMapSetter);
            }
        }
    }
}