using System;
using SqExpress;
using SqExpress.QueryBuilders.RecordSetter;
using SqExpress.IntTest.Tables;
using SqExpress.Syntax.Names;
using System.Collections.Generic;
using SqExpress.Syntax.Select.SelectItems;

namespace SqExpress.IntTest.Tables.Models
{
    public class TestMergeData
    {
        //Auto-generated by SqExpress Code-gen util
        public TestMergeData(int id, int value)
        {
            this.Id = id;
            this.Value = value;
        }

        //Auto-generated by SqExpress Code-gen util
        public static TestMergeData Read(ISqDataRecordReader record, TestMergeTmpTable table)
        {
            return new TestMergeData(id: table.Id.Read(record), value: table.Value.Read(record));
        }

        //Auto-generated by SqExpress Code-gen util
        public static TestMergeData ReadWithPrefix(ISqDataRecordReader record, TestMergeTmpTable table, string prefix)
        {
            return new TestMergeData(id: table.Id.Read(record, prefix + table.Id.ColumnName.Name), value: table.Value.Read(record, prefix + table.Value.ColumnName.Name));
        }

        //Auto-generated by SqExpress Code-gen util
        public static TestMergeData ReadOrdinal(ISqDataRecordReader record, TestMergeTmpTable table, int offset)
        {
            return new TestMergeData(id: table.Id.Read(record, offset), value: table.Value.Read(record, offset + 1));
        }

        //Auto-generated by SqExpress Code-gen util
        public int Id { get; }

        //Auto-generated by SqExpress Code-gen util
        public int Value { get; }

        //Auto-generated by SqExpress Code-gen util
        public TestMergeData WithId(int id)
        {
            return new TestMergeData(id: id, value: this.Value);
        }

        //Auto-generated by SqExpress Code-gen util
        public TestMergeData WithValue(int value)
        {
            return new TestMergeData(id: this.Id, value: value);
        }

        //Auto-generated by SqExpress Code-gen util
        public static TableColumn[] GetColumns(TestMergeTmpTable table)
        {
            return new TableColumn[]{table.Id, table.Value};
        }

        //Auto-generated by SqExpress Code-gen util
        public static ExprAliasedColumn[] GetColumnsWithPrefix(TestMergeTmpTable table, string prefix)
        {
            return new ExprAliasedColumn[]{table.Id.As(prefix + table.Id.ColumnName.Name), table.Value.As(prefix + table.Value.ColumnName.Name)};
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNull(ISqDataRecordReader record, TestMergeTmpTable table)
        {
            foreach (var column in GetColumns(table))
            {
                if (!record.IsDBNull(column.ColumnName.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNullWithPrefix(ISqDataRecordReader record, TestMergeTmpTable table, string prefix)
        {
            foreach (var column in GetColumnsWithPrefix(table, prefix))
            {
                if (!record.IsDBNull(column.Alias!.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetMapping(IDataMapSetter<TestMergeTmpTable, TestMergeData> s)
        {
            return s.Set(s.Target.Id, s.Source.Id).Set(s.Target.Value, s.Source.Value);
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetUpdateKeyMapping(IDataMapSetter<TestMergeTmpTable, TestMergeData> s)
        {
            return s.Set(s.Target.Id, s.Source.Id);
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetUpdateMapping(IDataMapSetter<TestMergeTmpTable, TestMergeData> s)
        {
            return s.Set(s.Target.Value, s.Source.Value);
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelReader<TestMergeData, TestMergeTmpTable> GetReader()
        {
            return TestMergeDataReader.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class TestMergeDataReader : ISqModelReader<TestMergeData, TestMergeTmpTable>
        {
            public static TestMergeDataReader Instance { get; } = new TestMergeDataReader();
            IReadOnlyList<ExprColumn> ISqModelReader<TestMergeData, TestMergeTmpTable>.GetColumns(TestMergeTmpTable table)
            {
                return TestMergeData.GetColumns(table);
            }

            TestMergeData ISqModelReader<TestMergeData, TestMergeTmpTable>.Read(ISqDataRecordReader record, TestMergeTmpTable table)
            {
                return TestMergeData.Read(record, table);
            }

            TestMergeData ISqModelReader<TestMergeData, TestMergeTmpTable>.ReadOrdinal(ISqDataRecordReader record, TestMergeTmpTable table, int offset)
            {
                return TestMergeData.ReadOrdinal(record, table, offset);
            }
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelUpdaterKey<TestMergeData, TestMergeTmpTable> GetUpdater()
        {
            return TestMergeDataUpdater.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class TestMergeDataUpdater : ISqModelUpdaterKey<TestMergeData, TestMergeTmpTable>
        {
            public static TestMergeDataUpdater Instance { get; } = new TestMergeDataUpdater();
            IRecordSetterNext ISqModelUpdater<TestMergeData, TestMergeTmpTable>.GetMapping(IDataMapSetter<TestMergeTmpTable, TestMergeData> dataMapSetter)
            {
                return TestMergeData.GetMapping(dataMapSetter);
            }

            IRecordSetterNext ISqModelUpdaterKey<TestMergeData, TestMergeTmpTable>.GetUpdateKeyMapping(IDataMapSetter<TestMergeTmpTable, TestMergeData> dataMapSetter)
            {
                return TestMergeData.GetUpdateKeyMapping(dataMapSetter);
            }

            IRecordSetterNext ISqModelUpdaterKey<TestMergeData, TestMergeTmpTable>.GetUpdateMapping(IDataMapSetter<TestMergeTmpTable, TestMergeData> dataMapSetter)
            {
                return TestMergeData.GetUpdateMapping(dataMapSetter);
            }
        }

        public int Version { get; }
    }
}