using System;
using SqExpress;
using SqExpress.QueryBuilders.RecordSetter;
using SqExpress.IntTest.Tables;
using SqExpress.Syntax.Names;
using System.Collections.Generic;
using SqExpress.Syntax.Select.SelectItems;

namespace SqExpress.IntTest.Tables.Models
{
    public class TestMergeDataRow
    {
        //Auto-generated by SqExpress Code-gen util
        public TestMergeDataRow(int id, int value, int version)
        {
            this.Id = id;
            this.Value = value;
            this.Version = version;
        }

        //Auto-generated by SqExpress Code-gen util
        public static TestMergeDataRow Read(ISqDataRecordReader record, TestMergeTmpTable table)
        {
            return new TestMergeDataRow(id: table.Id.Read(record), value: table.Value.Read(record), version: table.Version.Read(record));
        }

        //Auto-generated by SqExpress Code-gen util
        public static TestMergeDataRow ReadWithPrefix(ISqDataRecordReader record, TestMergeTmpTable table, string prefix)
        {
            return new TestMergeDataRow(id: table.Id.Read(record, prefix + table.Id.ColumnName.Name), value: table.Value.Read(record, prefix + table.Value.ColumnName.Name), version: table.Version.Read(record, prefix + table.Version.ColumnName.Name));
        }

        //Auto-generated by SqExpress Code-gen util
        public static TestMergeDataRow ReadOrdinal(ISqDataRecordReader record, TestMergeTmpTable table, int offset)
        {
            return new TestMergeDataRow(id: table.Id.Read(record, offset), value: table.Value.Read(record, offset + 1), version: table.Version.Read(record, offset + 2));
        }

        //Auto-generated by SqExpress Code-gen util
        public int Id { get; }

        //Auto-generated by SqExpress Code-gen util
        public int Value { get; }

        //Auto-generated by SqExpress Code-gen util
        public int Version { get; }

        //Auto-generated by SqExpress Code-gen util
        public TestMergeDataRow WithId(int id)
        {
            return new TestMergeDataRow(id: id, value: this.Value, version: this.Version);
        }

        //Auto-generated by SqExpress Code-gen util
        public TestMergeDataRow WithValue(int value)
        {
            return new TestMergeDataRow(id: this.Id, value: value, version: this.Version);
        }

        //Auto-generated by SqExpress Code-gen util
        public TestMergeDataRow WithVersion(int version)
        {
            return new TestMergeDataRow(id: this.Id, value: this.Value, version: version);
        }

        //Auto-generated by SqExpress Code-gen util
        public static TableColumn[] GetColumns(TestMergeTmpTable table)
        {
            return new TableColumn[]{table.Id, table.Value, table.Version};
        }

        //Auto-generated by SqExpress Code-gen util
        public static ExprAliasedColumn[] GetColumnsWithPrefix(TestMergeTmpTable table, string prefix)
        {
            return new ExprAliasedColumn[]{table.Id.As(prefix + table.Id.ColumnName.Name), table.Value.As(prefix + table.Value.ColumnName.Name), table.Version.As(prefix + table.Version.ColumnName.Name)};
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNull(ISqDataRecordReader record, TestMergeTmpTable table)
        {
            foreach (var column in GetColumns(table))
            {
                if (!record.IsDBNull(column.ColumnName.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNullWithPrefix(ISqDataRecordReader record, TestMergeTmpTable table, string prefix)
        {
            foreach (var column in GetColumnsWithPrefix(table, prefix))
            {
                if (!record.IsDBNull(column.Alias!.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetMapping(IDataMapSetter<TestMergeTmpTable, TestMergeDataRow> s)
        {
            return s.Set(s.Target.Id, s.Source.Id).Set(s.Target.Value, s.Source.Value).Set(s.Target.Version, s.Source.Version);
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetUpdateKeyMapping(IDataMapSetter<TestMergeTmpTable, TestMergeDataRow> s)
        {
            return s.Set(s.Target.Id, s.Source.Id);
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetUpdateMapping(IDataMapSetter<TestMergeTmpTable, TestMergeDataRow> s)
        {
            return s.Set(s.Target.Value, s.Source.Value).Set(s.Target.Version, s.Source.Version);
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelReader<TestMergeDataRow, TestMergeTmpTable> GetReader()
        {
            return TestMergeDataRowReader.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class TestMergeDataRowReader : ISqModelReader<TestMergeDataRow, TestMergeTmpTable>
        {
            public static TestMergeDataRowReader Instance { get; } = new TestMergeDataRowReader();
            IReadOnlyList<ExprColumn> ISqModelReader<TestMergeDataRow, TestMergeTmpTable>.GetColumns(TestMergeTmpTable table)
            {
                return TestMergeDataRow.GetColumns(table);
            }

            TestMergeDataRow ISqModelReader<TestMergeDataRow, TestMergeTmpTable>.Read(ISqDataRecordReader record, TestMergeTmpTable table)
            {
                return TestMergeDataRow.Read(record, table);
            }

            TestMergeDataRow ISqModelReader<TestMergeDataRow, TestMergeTmpTable>.ReadOrdinal(ISqDataRecordReader record, TestMergeTmpTable table, int offset)
            {
                return TestMergeDataRow.ReadOrdinal(record, table, offset);
            }
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelUpdaterKey<TestMergeDataRow, TestMergeTmpTable> GetUpdater()
        {
            return TestMergeDataRowUpdater.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class TestMergeDataRowUpdater : ISqModelUpdaterKey<TestMergeDataRow, TestMergeTmpTable>
        {
            public static TestMergeDataRowUpdater Instance { get; } = new TestMergeDataRowUpdater();
            IRecordSetterNext ISqModelUpdater<TestMergeDataRow, TestMergeTmpTable>.GetMapping(IDataMapSetter<TestMergeTmpTable, TestMergeDataRow> dataMapSetter)
            {
                return TestMergeDataRow.GetMapping(dataMapSetter);
            }

            IRecordSetterNext ISqModelUpdaterKey<TestMergeDataRow, TestMergeTmpTable>.GetUpdateKeyMapping(IDataMapSetter<TestMergeTmpTable, TestMergeDataRow> dataMapSetter)
            {
                return TestMergeDataRow.GetUpdateKeyMapping(dataMapSetter);
            }

            IRecordSetterNext ISqModelUpdaterKey<TestMergeDataRow, TestMergeTmpTable>.GetUpdateMapping(IDataMapSetter<TestMergeTmpTable, TestMergeDataRow> dataMapSetter)
            {
                return TestMergeDataRow.GetUpdateMapping(dataMapSetter);
            }
        }
    }
}