using System.Text.Json.Serialization;
using SqExpress.QueryBuilders.RecordSetter;
using SqExpress.Syntax.Names;
using System;
using SqExpress;
using SqExpress.IntTest.Tables;
using System.Collections.Generic;
using SqExpress.Syntax.Select.SelectItems;

namespace SqExpress.IntTest.Tables.Models
{
    public class UserEmail
    {
        //Auto-generated by SqExpress Code-gen util
        public UserEmail(EntUser id, string email)
        {
            this.Id = id;
            this.Email = email;
        }

        //Auto-generated by SqExpress Code-gen util
        public static UserEmail Read(ISqDataRecordReader record, TableItUser table)
        {
            return new UserEmail(id: (EntUser)table.UserId.Read(record), email: table.Email.Read(record));
        }

        //Auto-generated by SqExpress Code-gen util
        public static UserEmail ReadWithPrefix(ISqDataRecordReader record, TableItUser table, string prefix)
        {
            return new UserEmail(id: (EntUser)table.UserId.Read(record, prefix + table.UserId.ColumnName.Name), email: table.Email.Read(record, prefix + table.Email.ColumnName.Name));
        }

        //Auto-generated by SqExpress Code-gen util
        public static UserEmail ReadOrdinal(ISqDataRecordReader record, TableItUser table, int offset)
        {
            return new UserEmail(id: (EntUser)table.UserId.Read(record, offset), email: table.Email.Read(record, offset + 1));
        }

        [JsonPropertyName("id")]
        //Auto-generated by SqExpress Code-gen util
        public EntUser Id { get; }

        [JsonPropertyName("email")]
        //Auto-generated by SqExpress Code-gen util
        public string Email { get; }

        //Auto-generated by SqExpress Code-gen util
        public UserEmail WithId(EntUser id)
        {
            return new UserEmail(id: id, email: this.Email);
        }

        //Auto-generated by SqExpress Code-gen util
        public UserEmail WithEmail(string email)
        {
            return new UserEmail(id: this.Id, email: email);
        }

        //Auto-generated by SqExpress Code-gen util
        public static TableColumn[] GetColumns(TableItUser table)
        {
            return new TableColumn[]{table.UserId, table.Email};
        }

        //Auto-generated by SqExpress Code-gen util
        public static ExprAliasedColumn[] GetColumnsWithPrefix(TableItUser table, string prefix)
        {
            return new ExprAliasedColumn[]{table.UserId.As(prefix + table.UserId.ColumnName.Name), table.Email.As(prefix + table.Email.ColumnName.Name)};
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNull(ISqDataRecordReader record, TableItUser table)
        {
            foreach (var column in GetColumns(table))
            {
                if (!record.IsDBNull(column.ColumnName.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static bool IsNullWithPrefix(ISqDataRecordReader record, TableItUser table, string prefix)
        {
            foreach (var column in GetColumnsWithPrefix(table, prefix))
            {
                if (!record.IsDBNull(column.Alias!.Name))
                {
                    return false;
                }
            }

            return true;
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetMapping(IDataMapSetter<TableItUser, UserEmail> s)
        {
            return s.Set(s.Target.Email, s.Source.Email);
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetUpdateKeyMapping(IDataMapSetter<TableItUser, UserEmail> s)
        {
            return s.Set(s.Target.UserId, (int)s.Source.Id);
        }

        //Auto-generated by SqExpress Code-gen util
        public static IRecordSetterNext GetUpdateMapping(IDataMapSetter<TableItUser, UserEmail> s)
        {
            return s.Set(s.Target.Email, s.Source.Email);
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelReader<UserEmail, TableItUser> GetReader()
        {
            return UserEmailReader.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class UserEmailReader : ISqModelReader<UserEmail, TableItUser>
        {
            public static UserEmailReader Instance { get; } = new UserEmailReader();
            IReadOnlyList<ExprColumn> ISqModelReader<UserEmail, TableItUser>.GetColumns(TableItUser table)
            {
                return UserEmail.GetColumns(table);
            }

            UserEmail ISqModelReader<UserEmail, TableItUser>.Read(ISqDataRecordReader record, TableItUser table)
            {
                return UserEmail.Read(record, table);
            }

            UserEmail ISqModelReader<UserEmail, TableItUser>.ReadOrdinal(ISqDataRecordReader record, TableItUser table, int offset)
            {
                return UserEmail.ReadOrdinal(record, table, offset);
            }
        }

        //Auto-generated by SqExpress Code-gen util
        public static ISqModelUpdaterKey<UserEmail, TableItUser> GetUpdater()
        {
            return UserEmailUpdater.Instance;
        }

        //Auto-generated by SqExpress Code-gen util
        private class UserEmailUpdater : ISqModelUpdaterKey<UserEmail, TableItUser>
        {
            public static UserEmailUpdater Instance { get; } = new UserEmailUpdater();
            IRecordSetterNext ISqModelUpdater<UserEmail, TableItUser>.GetMapping(IDataMapSetter<TableItUser, UserEmail> dataMapSetter)
            {
                return UserEmail.GetMapping(dataMapSetter);
            }

            IRecordSetterNext ISqModelUpdaterKey<UserEmail, TableItUser>.GetUpdateKeyMapping(IDataMapSetter<TableItUser, UserEmail> dataMapSetter)
            {
                return UserEmail.GetUpdateKeyMapping(dataMapSetter);
            }

            IRecordSetterNext ISqModelUpdaterKey<UserEmail, TableItUser>.GetUpdateMapping(IDataMapSetter<TableItUser, UserEmail> dataMapSetter)
            {
                return UserEmail.GetUpdateMapping(dataMapSetter);
            }
        }
    }
}