using SqExpress.Syntax.Boolean;
using SqExpress.Syntax.Boolean.Predicate;
using SqExpress.Syntax.Expressions;
using SqExpress.Syntax.Functions;
using SqExpress.Syntax.Functions.Known;
using SqExpress.Syntax.Names;
using SqExpress.Syntax.Output;
using SqExpress.Syntax.Select;
using SqExpress.Syntax.Select.SelectItems;
using SqExpress.Syntax.Type;
using SqExpress.Syntax.Update;
using SqExpress.Syntax.Value;

namespace SqExpress.Syntax
{
    public interface IExprVisitor
    {
        //CodeGenStart
        void VisitExprAggregateFunction(ExprAggregateFunction expr);
        void VisitExprAggregateOverFunction(ExprAggregateOverFunction expr);
        void VisitExprAlias(ExprAlias expr);
        void VisitExprAliasGuid(ExprAliasGuid expr);
        void VisitExprAliasedColumn(ExprAliasedColumn expr);
        void VisitExprAliasedColumnName(ExprAliasedColumnName expr);
        void VisitExprAliasedSelecting(ExprAliasedSelecting expr);
        void VisitExprAliasedTableFunction(ExprAliasedTableFunction expr);
        void VisitExprAllColumns(ExprAllColumns expr);
        void VisitExprAnalyticFunction(ExprAnalyticFunction expr);
        void VisitExprBitwiseAnd(ExprBitwiseAnd expr);
        void VisitExprBitwiseNot(ExprBitwiseNot expr);
        void VisitExprBitwiseOr(ExprBitwiseOr expr);
        void VisitExprBitwiseXor(ExprBitwiseXor expr);
        void VisitExprBoolLiteral(ExprBoolLiteral expr);
        void VisitExprBooleanAnd(ExprBooleanAnd expr);
        void VisitExprBooleanEq(ExprBooleanEq expr);
        void VisitExprBooleanGt(ExprBooleanGt expr);
        void VisitExprBooleanGtEq(ExprBooleanGtEq expr);
        void VisitExprBooleanLt(ExprBooleanLt expr);
        void VisitExprBooleanLtEq(ExprBooleanLtEq expr);
        void VisitExprBooleanNot(ExprBooleanNot expr);
        void VisitExprBooleanNotEq(ExprBooleanNotEq expr);
        void VisitExprBooleanOr(ExprBooleanOr expr);
        void VisitExprByteArrayLiteral(ExprByteArrayLiteral expr);
        void VisitExprByteLiteral(ExprByteLiteral expr);
        void VisitExprCase(ExprCase expr);
        void VisitExprCaseWhenThen(ExprCaseWhenThen expr);
        void VisitExprCast(ExprCast expr);
        void VisitExprColumn(ExprColumn expr);
        void VisitExprColumnAlias(ExprColumnAlias expr);
        void VisitExprColumnName(ExprColumnName expr);
        void VisitExprColumnSetClause(ExprColumnSetClause expr);
        void VisitExprCrossedTable(ExprCrossedTable expr);
        void VisitExprCteQuery(ExprCteQuery expr);
        void VisitExprCurrentRowFrameBorder(ExprCurrentRowFrameBorder expr);
        void VisitExprDatabaseName(ExprDatabaseName expr);
        void VisitExprDateAdd(ExprDateAdd expr);
        void VisitExprDateDiff(ExprDateDiff expr);
        void VisitExprDateTimeLiteral(ExprDateTimeLiteral expr);
        void VisitExprDateTimeOffsetLiteral(ExprDateTimeOffsetLiteral expr);
        void VisitExprDbSchema(ExprDbSchema expr);
        void VisitExprDecimalLiteral(ExprDecimalLiteral expr);
        void VisitExprDefault(ExprDefault expr);
        void VisitExprDelete(ExprDelete expr);
        void VisitExprDeleteOutput(ExprDeleteOutput expr);
        void VisitExprDerivedTableQuery(ExprDerivedTableQuery expr);
        void VisitExprDerivedTableValues(ExprDerivedTableValues expr);
        void VisitExprDiv(ExprDiv expr);
        void VisitExprDoubleLiteral(ExprDoubleLiteral expr);
        void VisitExprExists(ExprExists expr);
        void VisitExprExprMergeNotMatchedInsert(ExprExprMergeNotMatchedInsert expr);
        void VisitExprExprMergeNotMatchedInsertDefault(ExprExprMergeNotMatchedInsertDefault expr);
        void VisitExprFrameClause(ExprFrameClause expr);
        void VisitExprFuncCoalesce(ExprFuncCoalesce expr);
        void VisitExprFuncIsNull(ExprFuncIsNull expr);
        void VisitExprFunctionName(ExprFunctionName expr);
        void VisitExprGetDate(ExprGetDate expr);
        void VisitExprGetUtcDate(ExprGetUtcDate expr);
        void VisitExprGuidLiteral(ExprGuidLiteral expr);
        void VisitExprIdentityInsert(ExprIdentityInsert expr);
        void VisitExprInSubQuery(ExprInSubQuery expr);
        void VisitExprInValues(ExprInValues expr);
        void VisitExprInsert(ExprInsert expr);
        void VisitExprInsertOutput(ExprInsertOutput expr);
        void VisitExprInsertQuery(ExprInsertQuery expr);
        void VisitExprInsertValueRow(ExprInsertValueRow expr);
        void VisitExprInsertValues(ExprInsertValues expr);
        void VisitExprInt16Literal(ExprInt16Literal expr);
        void VisitExprInt32Literal(ExprInt32Literal expr);
        void VisitExprInt64Literal(ExprInt64Literal expr);
        void VisitExprIsNull(ExprIsNull expr);
        void VisitExprJoinedTable(ExprJoinedTable expr);
        void VisitExprLateralCrossedTable(ExprLateralCrossedTable expr);
        void VisitExprLike(ExprLike expr);
        void VisitExprList(ExprList expr);
        void VisitExprMerge(ExprMerge expr);
        void VisitExprMergeMatchedDelete(ExprMergeMatchedDelete expr);
        void VisitExprMergeMatchedUpdate(ExprMergeMatchedUpdate expr);
        void VisitExprMergeOutput(ExprMergeOutput expr);
        void VisitExprModulo(ExprModulo expr);
        void VisitExprMul(ExprMul expr);
        void VisitExprNull(ExprNull expr);
        void VisitExprOffsetFetch(ExprOffsetFetch expr);
        void VisitExprOrderBy(ExprOrderBy expr);
        void VisitExprOrderByItem(ExprOrderByItem expr);
        void VisitExprOrderByOffsetFetch(ExprOrderByOffsetFetch expr);
        void VisitExprOutput(ExprOutput expr);
        void VisitExprOutputAction(ExprOutputAction expr);
        void VisitExprOutputColumn(ExprOutputColumn expr);
        void VisitExprOutputColumnDeleted(ExprOutputColumnDeleted expr);
        void VisitExprOutputColumnInserted(ExprOutputColumnInserted expr);
        void VisitExprOver(ExprOver expr);
        void VisitExprQueryExpression(ExprQueryExpression expr);
        void VisitExprQueryList(ExprQueryList expr);
        void VisitExprQuerySpecification(ExprQuerySpecification expr);
        void VisitExprScalarFunction(ExprScalarFunction expr);
        void VisitExprSchemaName(ExprSchemaName expr);
        void VisitExprSelect(ExprSelect expr);
        void VisitExprSelectOffsetFetch(ExprSelectOffsetFetch expr);
        void VisitExprStringConcat(ExprStringConcat expr);
        void VisitExprStringLiteral(ExprStringLiteral expr);
        void VisitExprSub(ExprSub expr);
        void VisitExprSum(ExprSum expr);
        void VisitExprTable(ExprTable expr);
        void VisitExprTableAlias(ExprTableAlias expr);
        void VisitExprTableFullName(ExprTableFullName expr);
        void VisitExprTableFunction(ExprTableFunction expr);
        void VisitExprTableName(ExprTableName expr);
        void VisitExprTableValueConstructor(ExprTableValueConstructor expr);
        void VisitExprTempTableName(ExprTempTableName expr);
        void VisitExprTypeBoolean(ExprTypeBoolean expr);
        void VisitExprTypeByte(ExprTypeByte expr);
        void VisitExprTypeByteArray(ExprTypeByteArray expr);
        void VisitExprTypeDateTime(ExprTypeDateTime expr);
        void VisitExprTypeDateTimeOffset(ExprTypeDateTimeOffset expr);
        void VisitExprTypeDecimal(ExprTypeDecimal expr);
        void VisitExprTypeDouble(ExprTypeDouble expr);
        void VisitExprTypeFixSizeByteArray(ExprTypeFixSizeByteArray expr);
        void VisitExprTypeFixSizeString(ExprTypeFixSizeString expr);
        void VisitExprTypeGuid(ExprTypeGuid expr);
        void VisitExprTypeInt16(ExprTypeInt16 expr);
        void VisitExprTypeInt32(ExprTypeInt32 expr);
        void VisitExprTypeInt64(ExprTypeInt64 expr);
        void VisitExprTypeString(ExprTypeString expr);
        void VisitExprTypeXml(ExprTypeXml expr);
        void VisitExprUnboundedFrameBorder(ExprUnboundedFrameBorder expr);
        void VisitExprUnsafeValue(ExprUnsafeValue expr);
        void VisitExprUpdate(ExprUpdate expr);
        void VisitExprValueFrameBorder(ExprValueFrameBorder expr);
        void VisitExprValueQuery(ExprValueQuery expr);
        void VisitExprValueRow(ExprValueRow expr);
        //CodeGenEnd
    }
}
