#if NET
using System;
using System.Collections.Generic;
using System.Data.SqlClient;
using System.IO;
using System.Linq;
using System.Reflection;
using System.Threading.Tasks;
using Castle.Core.Internal;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.VisualStudio.TestPlatform.PlatformAbstractions;
using NUnit.Framework;
using SqExpress.CodeGen.Shared;
using SqExpress.CodeGenUtil.CodeGen;
using SqExpress.CodeGenUtil;
using SqExpress.DbMetadata.Internal.DbManagers;
using SqExpress.DbMetadata.Internal.Model;
using SqExpress.SqlExport;

namespace SqExpress.Test.CodeGenUtil
{
    [TestFixture]
    public class TableClassGeneratorTest
    {
        [Test]
        public async Task BasicTest()
        {
            var genTablesOptions = new GenTablesOptions(ConnectionType.MsSql, "fake", "Tab", "", "MyTables", verbosity: Verbosity.Quiet);
            using var dbManager = new DbManager(new DbManagerTest(),
                new SqlConnection("Initial Catalog=_1_2_3tbl;"),
                new DbManagerOptions(genTablesOptions.TableClassPrefix));

            var tables = await dbManager.SelectTables();

            Assert.AreEqual(2, tables.Count);

            var tableMap = tables.ToDictionary(t => t.DbName);

            IReadOnlyDictionary<TableRef, ClassDeclarationSyntax> existingCode =
                new Dictionary<TableRef, ClassDeclarationSyntax>();

            var trees = tables.Select(t => CSharpSyntaxTree.Create(
                CodeGenTableDescriptorSupport.GenerateTableDescriptor(
                    t,
                    tableMap,
                    "MyCompany.MyProject.Tables",
                    existingCode,
                    out _))).ToList();

            var tableZSource = trees.First(t => t.GetText().ToString().Contains("partial class TabTableZ", StringComparison.Ordinal)).GetText().ToString();
            var tableASource = trees.First(t => t.GetText().ToString().Contains("partial class TabTableA", StringComparison.Ordinal)).GetText().ToString();

            Assert.AreEqual(NormalizeNewLines(
                """
                // <auto-generated/>
                #nullable enable
                using SqExpress;
                using SqExpress.Syntax.Type;

                namespace MyCompany.MyProject.Tables
                {
                    public partial class TabTableZ : TableBase
                    {
                        public TabTableZ() : this(alias: SqExpress.Alias.Auto)
                        {
                        }

                        public TabTableZ(Alias alias) : base("dbo", "TableZ", alias)
                        {
                            this.Id = this.CreateInt32Column("Id", ColumnMeta.PrimaryKey().Identity().DefaultValue(0));
                            this.ValueA = this.CreateStringColumn(name: "ValueA", size: 255, isUnicode: true, isText: false, columnMeta: ColumnMeta.DefaultValue(""));
                            this.ValueANo2 = this.CreateNullableDecimalColumn("Value_A", new DecimalPrecisionScale(precision: 2, scale: 6), null);
                        }

                        public Int32TableColumn Id { get; }
                        public StringTableColumn ValueA { get; }
                        public NullableDecimalTableColumn ValueANo2 { get; }
                    }
                }
                """),
                NormalizeNewLines(tableZSource));

            Assert.AreEqual(NormalizeNewLines(
                """
                // <auto-generated/>
                #nullable enable
                using SqExpress;
                using SqExpress.Syntax.Type;

                namespace MyCompany.MyProject.Tables
                {
                    public partial class TabTableA : TableBase
                    {
                        public TabTableA() : this(alias: SqExpress.Alias.Auto)
                        {
                        }

                        public TabTableA(Alias alias) : base("dbo", "TableA", alias)
                        {
                            this.Id = this.CreateInt32Column("Id", ColumnMeta.PrimaryKey().Identity().DefaultValue(0).ForeignKey<TabTableZ>(t => t.Id));
                            this.Value = this.CreateDateTimeColumn("Value", false, ColumnMeta.DefaultValue(SqQueryBuilder.GetUtcDate()));
                            this.IsActive = this.CreateBooleanColumn("IsActive", ColumnMeta.DefaultValue(true));
                            this.AddUniqueIndex(IndexMetaColumn.Desc(this.Value));
                        }

                        public Int32TableColumn Id { get; }
                        public DateTimeTableColumn Value { get; }
                        public BooleanTableColumn IsActive { get; }
                    }
                }
                """),
                NormalizeNewLines(tableASource));

            var compilation = CSharpCompilation.Create("Tables",
                trees,
                options: new CSharpCompilationOptions(OutputKind.DynamicallyLinkedLibrary));

            compilation = compilation.AddReferences(
                MetadataReference.CreateFromFile(Assembly.Load("netstandard, Version=2.0.0.0").Location),
                MetadataReference.CreateFromFile(typeof(object).Assembly.GetAssemblyLocation()),
                MetadataReference.CreateFromFile(Assembly
                    .Load("System.Runtime, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")
                    .Location),
                MetadataReference.CreateFromFile(typeof(SqQueryBuilder).Assembly.GetAssemblyLocation()));

            MemoryStream ms = new MemoryStream();

            var emitResult = compilation.Emit(ms);
            if (!emitResult.Success)
            {
                Assert.Fail(emitResult.Diagnostics.FirstOrDefault()?.GetMessage());
            }

            var assembly = Assembly.Load(ms.ToArray());

            var allTypes = assembly.GetTypes();

            var table1 = (TableBase) Activator.CreateInstance(allTypes.Find(t => t.Name == tables[0].Name))!;
            Assert.NotNull(table1);
            var table2 = (TableBase) Activator.CreateInstance(allTypes.Find(t => t.Name == tables[1].Name))!;
            Assert.NotNull(table2);


            string table1ExpectedSql =
                "CREATE TABLE [dbo].[TableZ]([Id] int NOT NULL  IDENTITY (1, 1) DEFAULT (0),[ValueA] [nvarchar](255) NOT NULL DEFAULT (''),[Value_A] decimal(2,6),CONSTRAINT [PK_dbo_TableZ] PRIMARY KEY ([Id]));";
            Assert.AreEqual(table1ExpectedSql, TSqlExporter.Default.ToSql(table1.Script.Create()));

            string table2ExpectedSql =
                "CREATE TABLE [dbo].[TableA]([Id] int NOT NULL  IDENTITY (1, 1) DEFAULT (0),[Value] datetime NOT NULL DEFAULT (GETUTCDATE()),[IsActive] bit NOT NULL DEFAULT (1),CONSTRAINT [PK_dbo_TableA] PRIMARY KEY ([Id]),CONSTRAINT [FK_dbo__TableA_to_dbo__TableZ] FOREIGN KEY ([Id]) REFERENCES [dbo].[TableZ]([Id]),INDEX [IX_dbo_TableA_Value_DESC] UNIQUE([Value] DESC));";
            Assert.AreEqual(table2ExpectedSql, TSqlExporter.Default.ToSql(table2.Script.Create()));
        }

        [Test]
        public async Task AttributeDeclarationBasicTest()
        {
            var genTablesOptions = new GenTablesOptions(ConnectionType.MsSql, "fake", "Tab", "", "MyTables", verbosity: Verbosity.Quiet, useTableDeclarationAttributes: true);
            using var dbManager = new DbManager(new DbManagerTest(),
                new SqlConnection("Initial Catalog=_1_2_3tbl;"),
                new DbManagerOptions(genTablesOptions.TableClassPrefix));

            var tables = await dbManager.SelectTables();
            var tableMap = tables.ToDictionary(t => t.DbName);

            var sources = tables.Select(t => CodeGenTableDescriptorSupport.GenerateTableDeclaration(t, tableMap, "MyCompany.MyProject.Tables").ToFullString()).ToList();
            var tableZSource = sources.First(s => s.Contains("partial class TabTableZ", StringComparison.Ordinal));
            var tableASource = sources.First(s => s.Contains("partial class TabTableA", StringComparison.Ordinal));

            Assert.AreEqual(NormalizeNewLines(
                """
                // <auto-generated/>
                #nullable enable
                using SqExpress.TableDecalationAttributes;

                namespace MyCompany.MyProject.Tables
                {
                    [TableDescriptor("dbo", "TableZ")]
                    [Int32Column("Id", Pk = true, Identity = true, DefaultValue = "0")]
                    [StringColumn("ValueA", Unicode = true, MaxLength = 255, DefaultValue = "")]
                    [NullableDecimalColumn("Value_A", PropertyName = "ValueANo2", Precision = 2, Scale = 6)]
                    public partial class TabTableZ
                    {
                    }
                }
                """),
                NormalizeNewLines(tableZSource));

            Assert.AreEqual(NormalizeNewLines(
                """
                // <auto-generated/>
                #nullable enable
                using SqExpress.TableDecalationAttributes;

                namespace MyCompany.MyProject.Tables
                {
                    [TableDescriptor("dbo", "TableA")]
                    [Int32Column("Id", Pk = true, Identity = true, FkTable = "TableZ", FkColumn = "Id", DefaultValue = "0")]
                    [DateTimeColumn("Value", DefaultValue = "$utcNow")]
                    [BooleanColumn("IsActive", DefaultValue = "1")]
                    [Index("Value", Unique = true, DescendingColumns = new string[] { "Value" })]
                    public partial class TabTableA
                    {
                    }
                }
                """),
                NormalizeNewLines(tableASource));
        }

        [Test]
        public async Task AllTablesStaticListTest()
        {
            var genTablesOptions = new GenTablesOptions(ConnectionType.MsSql, "fake", "Tab", "", "MyTables", verbosity: Verbosity.Quiet);
            using var dbManager = new DbManager(new DbManagerTest(),
                new SqlConnection("Initial Catalog=_1_2_3tbl;"),
                new DbManagerOptions(genTablesOptions.TableClassPrefix));

            var tables = await dbManager.SelectTables();

            var fileSystem = new TestFileSystem();
            var allTablesSource = TableListClassGenerator.Generate(
                @"C:\Temp\AllTables.cs",
                tables,
                "MyCompany.MyProject.Tables",
                genTablesOptions.TableClassPrefix,
                fileSystem).ToFullString();

            Assert.That(NormalizeNewLines(allTablesSource), Does.Contain("using System;\n"));
            Assert.That(NormalizeNewLines(allTablesSource), Does.Contain("using System.Collections.Generic;\n"));
            Assert.That(NormalizeNewLines(allTablesSource), Does.Contain("using SqExpress;\n"));
            Assert.That(NormalizeNewLines(allTablesSource), Does.Contain("public static readonly IReadOnlyCollection<TableBase> StaticList = Array.AsReadOnly(BuildAllTableList());"));
            Assert.That(NormalizeNewLines(allTablesSource), Does.Contain("public static TableBase[] BuildAllTableList() => new TableBase[]"));
            Assert.That(NormalizeNewLines(allTablesSource), Does.Contain("public static TabTableZ GetTableZ(Alias alias) => new TabTableZ(alias);"));
            Assert.That(NormalizeNewLines(allTablesSource), Does.Contain("public static TabTableA GetTableA() => new TabTableA(Alias.Auto);"));
        }

        [Test]
        public async Task AttributeDeclarationExistingClassIsMerged()
        {
            using var dbManager = new DbManager(new DbManagerTest(),
                new SqlConnection("Initial Catalog=_1_2_3tbl;"),
                new DbManagerOptions("Tab"));

            var tables = await dbManager.SelectTables();
            var tableMap = tables.ToDictionary(t => t.DbName);
            var table = tables.Single(t => t.Name == "TabTableZ");

            var existingCompilationUnit = CSharpSyntaxTree.ParseText(
                """
                using SqExpress.TableDecalationAttributes;

                namespace MyCompany.MyProject.Tables
                {
                    public partial class TabTableZ
                    {
                        public string CustomMethod()
                        {
                            return "Keep me";
                        }
                    }
                }
                """).GetCompilationUnitRoot();

            var updatedSource = CodeGenTableDescriptorSupport.GenerateTableDeclaration(
                table,
                tableMap,
                "MyCompany.MyProject.Tables",
                existingCompilationUnit).ToFullString();

            Assert.That(NormalizeNewLines(updatedSource), Does.Contain("[TableDescriptor(\"dbo\", \"TableZ\")]"));
            Assert.That(NormalizeNewLines(updatedSource), Does.Contain("[Int32Column(\"Id\", Pk = true, Identity = true, DefaultValue = \"0\")]"));
            Assert.That(NormalizeNewLines(updatedSource), Does.Contain("public string CustomMethod()"));
            Assert.That(NormalizeNewLines(updatedSource), Does.Contain("return \"Keep me\";"));
        }

        private static string NormalizeNewLines(string value)
            => value.Replace("\r\n", "\n");
    }
}
#endif
