using SqExpress.Syntax;
using SqExpress.Syntax.Json;
using SqExpress.Syntax.Type;

namespace SqExpress.SqlExport.Internal;

internal partial class SqliteBuilder
{
    public override bool VisitExprJsonValue(ExprJsonValue expr,IExpr? parent){this.FormattingWriter.Append("CASE WHEN json_type(");expr.Document.Accept(this,expr);this.CommaString(expr.Path);this.FormattingWriter.Append(") IN (");var kind=expr.ReturningType==null||expr.ReturningType is ExprTypeString?"'text'":expr.ReturningType is ExprTypeBoolean?"'true','false'":expr.ReturningType is ExprTypeInt32 or ExprTypeInt64?"'integer'":"'integer','real'";this.FormattingWriter.Append(kind);if(expr.ReturningType is ExprTypeInt32){this.FormattingWriter.Append(") AND json_extract(");expr.Document.Accept(this,expr);this.CommaString(expr.Path);this.FormattingWriter.Append(") BETWEEN -2147483648 AND 2147483647");}else this.FormattingWriter.Append(')');this.FormattingWriter.Append(" THEN ");if(expr.ReturningType!=null){this.FormattingWriter.Append("CAST(");}this.FormattingWriter.Append("json_extract(");expr.Document.Accept(this,expr);this.CommaString(expr.Path);this.FormattingWriter.Append(')');if(expr.ReturningType!=null){this.FormattingWriter.Append(" AS ");expr.ReturningType.Accept(this,expr);this.FormattingWriter.Append(')');}this.FormattingWriter.Append(" END");return true;}
    public override bool VisitExprJsonQuery(ExprJsonQuery expr,IExpr? parent){this.FormattingWriter.Append("CASE WHEN json_type(");expr.Document.Accept(this,expr);this.CommaString(expr.Path);this.FormattingWriter.Append(") IN ('object','array') THEN json(json_extract(");expr.Document.Accept(this,expr);this.CommaString(expr.Path);this.FormattingWriter.Append(")) END");return true;}
    public override bool VisitExprJsonNull(ExprJsonNull expr,IExpr? parent){this.FormattingWriter.Append("json('null')");return true;}
    public override bool VisitExprJsonSet(ExprJsonSet expr,IExpr? parent){this.FormattingWriter.Append("json_set(");expr.Document.Accept(this,expr);this.CommaString(expr.Path);this.FormattingWriter.Append(',');if(expr.Value is ExprJson){this.FormattingWriter.Append("json(");expr.Value.Accept(this,expr);this.FormattingWriter.Append(')');}else expr.Value.Accept(this,expr);this.FormattingWriter.Append(')');return true;}
    public override bool VisitExprJsonRemove(ExprJsonRemove expr,IExpr? parent){this.FormattingWriter.Append("json_remove(");expr.Document.Accept(this,expr);this.CommaString(expr.Path);this.FormattingWriter.Append(')');return true;}
    public override bool VisitExprJsonMember(ExprJsonMember expr,IExpr? parent){this.String(expr.Name);this.FormattingWriter.Append(',');if(expr.Value is ExprJson){this.FormattingWriter.Append("json(");expr.Value.Accept(this,expr);this.FormattingWriter.Append(')');}else expr.Value.Accept(this,expr);return true;}
    public override bool VisitExprJsonObject(ExprJsonObject expr,IExpr? parent){this.FormattingWriter.Append("json_object(");for(var i=0;i<expr.Members.Count;i++){if(i>0)this.FormattingWriter.Append(',');expr.Members[i].Accept(this,expr);}this.FormattingWriter.Append(')');return true;}
    public override bool VisitExprJsonArray(ExprJsonArray expr,IExpr? parent){this.FormattingWriter.Append("json_array(");for(var i=0;i<expr.Items.Count;i++){if(i>0)this.FormattingWriter.Append(',');if(expr.Items[i] is ExprJson){this.FormattingWriter.Append("json(");expr.Items[i].Accept(this,expr);this.FormattingWriter.Append(')');}else expr.Items[i].Accept(this,expr);}this.FormattingWriter.Append(')');return true;}
    public override bool VisitExprJsonTable(ExprJsonTable expr,IExpr? parent){this.FormattingWriter.Append("(SELECT ");for(var i=0;i<expr.Columns.Count;i++){if(i>0)this.FormattingWriter.Append(',');expr.Columns[i].Accept(this,expr);this.FormattingWriter.Append(' ');expr.Columns[i].Name.Accept(this,expr);}this.FormattingWriter.Append(" FROM json_each(");expr.Document.Accept(this,expr);this.CommaString(expr.Path);this.FormattingWriter.Append(") J) ");expr.Alias.Accept(this,expr);return true;}
    public override bool VisitExprJsonTableValueColumn(ExprJsonTableValueColumn expr,IExpr? parent){this.FormattingWriter.Append("CASE WHEN json_type(J.value,");this.String(expr.Path);this.FormattingWriter.Append(") IN (");this.FormattingWriter.Append(expr.SqlType is ExprTypeString?"'text'":expr.SqlType is ExprTypeBoolean?"'true','false'":expr.SqlType is ExprTypeInt32 or ExprTypeInt64?"'integer'":"'integer','real'");this.FormattingWriter.Append(") THEN CAST(json_extract(J.value,");this.String(expr.Path);this.FormattingWriter.Append(") AS ");expr.SqlType.Accept(this,expr);this.FormattingWriter.Append(") END");return true;}
    public override bool VisitExprJsonTableQueryColumn(ExprJsonTableQueryColumn expr,IExpr? parent){this.FormattingWriter.Append("CASE WHEN json_type(J.value,");this.String(expr.Path);this.FormattingWriter.Append(") IN ('object','array') THEN json(json_extract(J.value,");this.String(expr.Path);this.FormattingWriter.Append(")) END");return true;}
    public override bool VisitExprJsonTableOrdinalColumn(ExprJsonTableOrdinalColumn expr,IExpr? parent){this.FormattingWriter.Append("CAST(J.key AS integer)");return true;}
    public override bool VisitExprQueryAsJson(ExprQueryAsJson expr,IExpr? parent){var shape=JsonOutputShape.Build(expr.Query);this.FormattingWriter.Append(expr.WithoutArrayWrapper?"SELECT CASE COUNT(*) WHEN 0 THEN NULL WHEN 1 THEN json_extract(json_group_array(json(":"SELECT COALESCE(json_group_array(json(");this.SqliteRowObject(shape,expr.IncludeNullValues);this.FormattingWriter.Append(expr.WithoutArrayWrapper?")),'$[0]') ELSE json('!') END Json FROM (":")),'[]') Json FROM (");this.RenderForJsonSource(expr.Query,expr);this.FormattingWriter.Append(") J0");return true;}
    private void SqliteRowObject(System.Collections.Generic.IReadOnlyList<JsonOutputShape> nodes,bool includeNullValues){if(!includeNullValues)this.FormattingWriter.Append("json_patch('{}',");this.FormattingWriter.Append("json_object(");this.SqliteShape(nodes);this.FormattingWriter.Append(')');if(!includeNullValues)this.FormattingWriter.Append(')');}
    private void SqliteShape(System.Collections.Generic.IReadOnlyList<JsonOutputShape> nodes){for(var i=0;i<nodes.Count;i++){if(i>0)this.FormattingWriter.Append(',');var c=nodes[i];this.String(c.Name);this.FormattingWriter.Append(',');if(c.ColumnName!=null){if(c.IsJson)this.FormattingWriter.Append("json(");this.FormattingWriter.Append("J0.");this.AppendName(c.ColumnName);if(c.IsJson)this.FormattingWriter.Append(')');}else{this.FormattingWriter.Append("json_object(");this.SqliteShape(c.Children);this.FormattingWriter.Append(')');}}}
    private void CommaString(string value){this.FormattingWriter.Append(',');this.String(value);}
    private void String(string value){this.FormattingWriter.Append('\'');this.FormattingWriter.AppendEscapedSingleQuote(value);this.FormattingWriter.Append('\'');}
}
